<section class="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <div><h3 class="text-lg font-bold">Kartu Stok — {{ $card->ingredient_name_snapshot }}</h3><p class="text-sm text-slate-500">{{ $card->code }} · Saldo {{ $card->balance_quantity === null ? 'Periksa satuan' : number_format($card->balance_quantity, 3, ',', '.') }} {{ $card->unit_snapshot }} · {{ $card->active_lot_count }} lot aktif</p></div>
        <a href="{{ route('v3.warehouse.stock.export', ['bahan' => $card->ingredient_id]) }}" class="rounded-xl bg-sky-700 px-4 py-3 text-xs font-bold text-white">Ekspor mutasi CSV</a>
        <button wire:click="$set('ingredientId', null)" class="rounded-xl border px-4 py-3 text-xs font-bold">Tutup detail</button>
    </div>
    <h4 class="font-bold">Daftar lot</h4>
    <div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead><tr class="border-b"><th class="p-3">Lot internal / supplier</th><th class="p-3">Tanggal terima</th><th class="p-3">Kedaluwarsa</th><th class="p-3">Lokasi</th><th class="p-3">Saldo lot</th><th class="p-3">Status</th></tr></thead><tbody>
        @foreach($cardLots as $lot)<tr class="border-b"><td class="p-3">#{{ $lot->id }} · {{ $lot->lot_number ?: 'Tanpa nomor supplier' }}</td><td class="p-3">{{ \Illuminate\Support\Carbon::parse($lot->receiptItem?->receipt?->receipt_date ?? $lot->received_date ?? $lot->created_at)->format('d M Y') }}</td><td class="p-3">{{ $lot->expired_date?->format('d M Y') ?: '—' }}</td><td class="p-3">{{ $lot->location_name }} · {{ $lot->storage_type }}</td><td class="p-3">{{ number_format((float) $lot->balance_quantity, 3, ',', '.') }} {{ $lot->unit_snapshot }}</td><td class="p-3">{{ ['available'=>'Tersedia','depleted'=>'Habis','quarantine'=>'Karantina','rejected'=>'Ditolak'][$lot->status] ?? $lot->status }}</td></tr>@endforeach
    </tbody></table></div>
    <h4 class="font-bold">Riwayat mutasi · {{ $card->unit_snapshot }}</h4>
    <div class="overflow-x-auto"><table class="w-full min-w-[950px] text-left text-sm"><thead><tr class="border-b"><th class="p-3">Tanggal</th><th class="p-3">Jenis / referensi</th><th class="p-3">Masuk</th><th class="p-3">Keluar</th><th class="p-3">Saldo berjalan</th><th class="p-3">Lot</th><th class="p-3">Catatan</th></tr></thead><tbody>
        @foreach($ledger as $movement)<tr class="border-b"><td class="p-3">{{ $movement->movement_date?->format('d M Y') }}</td><td class="p-3">{{ $types[$movement->movement_type] ?? $movement->movement_type }}<br>{{ $movement->reference_number }}</td><td class="p-3">{{ $movement->card_quantity_in === null ? '—' : number_format($movement->card_quantity_in, 3, ',', '.') }}</td><td class="p-3">{{ $movement->card_quantity_out === null ? '—' : number_format($movement->card_quantity_out, 3, ',', '.') }}</td><td class="p-3 font-bold">{{ $movement->running_balance === null ? 'Periksa satuan' : number_format($movement->running_balance, 3, ',', '.') }}</td><td class="p-3">#{{ $movement->inventory_lot_id }} · {{ $movement->supplier_batch_number ?: '—' }}</td><td class="p-3">{{ $movement->notes ?: '—' }}</td></tr>@endforeach
    </tbody></table></div>
</section>
