<x-v3.shell :$unit :$navigation :$roleLabel title="Kebersihan" eyebrow="Checklist harian dan rekap periode">
    <div class="mx-auto max-w-[1500px] space-y-5 text-slate-900 dark:text-slate-100">
        <x-v3.flash-alert />
        <div><p class="text-xs font-bold uppercase tracking-[.18em] text-sky-600">Divisi Kebersihan</p><h2 class="mt-2 text-2xl font-bold">Pekerjaan Kebersihan Harian</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Checklist hari ini dibuat otomatis dari master area. Format resmi periode dapat diekspor per Toilet, Produksi, Pemorsian, dan tiga Gudang.</p></div>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900">
            <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h3 class="font-bold">Ekspor checklist periode</h3><p class="mt-1 text-xs text-slate-500">Maksimal 10 hari kerja dalam satu formulir.</p></div><div class="grid gap-3 sm:grid-cols-2"><label><span class="mb-1 block text-xs font-semibold">Mulai</span><input wire:model.live="periodStart" type="date" class="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950"></label><label><span class="mb-1 block text-xs font-semibold">Selesai</span><input wire:model.live="periodEnd" type="date" class="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950"></label></div></div>
            <div class="mt-4 flex flex-wrap gap-2">@foreach($cleaningAreas as $area)@if(App\Support\CleaningChecklistTemplate::supportsPeriodExport($area))<a target="_blank" href="{{ route('v3.cleaning.checklist-period.pdf', ['cleaningArea'=>$area,'start_date'=>$periodStart,'end_date'=>$periodEnd]) }}" class="inline-flex h-9 items-center rounded-xl border border-slate-200 px-3 text-xs font-bold hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">{{ $area->name }}</a>@endif @endforeach @if($cleaningAreas->where('template_type','warehouse')->isNotEmpty())<a target="_blank" href="{{ route('v3.cleaning.warehouse-checklists.pdf', ['start_date'=>$periodStart,'end_date'=>$periodEnd]) }}" class="inline-flex h-9 items-center rounded-xl bg-slate-800 px-3 text-xs font-bold text-white dark:bg-sky-600">Gabungkan 3 Gudang</a>@endif</div>
        </section>
        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            @forelse($records as $record)@php($progress=$record->completion_percentage)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.13em] text-sky-600">{{ $record->scheduled_date?->format('d/m/Y') }}</p><h3 class="mt-1 text-lg font-bold">{{ $record->cleaningArea?->name }}</h3><p class="mt-1 text-xs text-slate-500">{{ $record->petugas_name_snapshot ?: 'Belum diambil petugas' }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold dark:bg-slate-700">{{ $record->state->label() }}</span></div><div class="mt-4"><div class="flex justify-between text-xs"><span>Checklist</span><strong>{{ $progress }}%</strong></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-sky-500" style="width:{{ $progress }}%"></div></div></div><div class="mt-4 flex items-center justify-between"><span class="text-xs text-slate-500">Laporan: {{ $record->status->label() }}</span><a wire:navigate href="{{ route('v3.operations.show',['module'=>'kebersihan','record'=>$record]) }}" class="text-xs font-bold text-sky-600">Buka checklist</a></div></article>
            @empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-900">Belum ada pekerjaan Kebersihan.</div>@endforelse
        </section><div>{{ $records->links() }}</div>
    </div>
</x-v3.shell>
