<x-v3.shell :$unit :$navigation :$roleLabel title="Checklist Kebersihan" eyebrow="{{ $record?->cleaningArea?->name ?? 'Area Kebersihan' }}">
    @php($input='h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950 disabled:opacity-60')
    @php($textarea='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950 disabled:opacity-60')
    @php($state=$record?->state?->value)
    @php($workEditable=$editable && $canUpdate && in_array($state,['in_progress','ready'],true))
    <div class="mx-auto max-w-[1250px] space-y-5 text-slate-900 dark:text-slate-100">
        @if($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200">{{ $actionMessage }}</div>@endif
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-200">{{ $message }}</div>@enderror
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><p class="text-xs font-bold uppercase tracking-[.15em] text-sky-600">{{ $record?->session_number }}</p><h2 class="mt-1 text-2xl font-bold">{{ $record?->cleaningArea?->name }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ $record?->scheduled_date?->translatedFormat('l, d F Y') }} · {{ $record?->cleaningArea?->location }}</p></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold dark:bg-slate-700">{{ $record?->state?->label() }}</span><span class="rounded-full bg-sky-100 px-3 py-1.5 text-xs font-bold text-sky-700 dark:bg-sky-500/15 dark:text-sky-300">{{ $record?->status?->label() }}</span></div></div><div class="mt-5 grid gap-3 md:grid-cols-3"><div class="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p class="text-[10px] font-bold uppercase text-slate-500">Petugas</p><p class="mt-1 text-sm font-bold">{{ $record?->petugas_name_snapshot ?: 'Belum diambil' }}</p></div><div class="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p class="text-[10px] font-bold uppercase text-slate-500">Mulai</p><p class="mt-1 text-sm font-bold">{{ $record?->started_at?->format('H:i') ?: '-' }}</p></div><div class="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p class="text-[10px] font-bold uppercase text-slate-500">Selesai</p><p class="mt-1 text-sm font-bold">{{ $record?->completed_at?->format('H:i') ?: '-' }}</p></div></div></section>

        @if($state==='planned' && $canUpdate)<section class="rounded-2xl border border-sky-200 bg-sky-50 p-5 dark:border-sky-500/30 dark:bg-sky-500/10"><h3 class="font-bold text-sky-900 dark:text-sky-100">Pekerjaan belum dimulai</h3><p class="mt-1 text-sm text-sky-700 dark:text-sky-200">Petugas otomatis diambil dari akun yang menekan tombol.</p><div class="mt-4 flex justify-end"><button wire:click="workflow('start')" wire:confirm="Mulai pekerjaan kebersihan area ini?" class="h-11 rounded-xl bg-sky-600 px-5 text-xs font-bold text-white">Mulai kebersihan</button></div></section>@endif

        <form wire:submit="save" class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="grid gap-4 md:grid-cols-2"><label><span class="mb-1 block text-xs font-semibold">Kondisi awal (opsional)</span><textarea wire:model="data.before_condition" rows="3" @disabled(!$workEditable) class="{{ $textarea }}"></textarea></label><label><span class="mb-1 block text-xs font-semibold">Evaluasi kebersihan</span><textarea wire:model="data.after_condition" rows="3" @disabled(!$workEditable) class="{{ $textarea }}" placeholder="Ringkasan hasil atau masalah pada hari ini"></textarea></label></div></section>

            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-700"><h3 class="font-bold">Checklist area</h3><p class="mt-1 text-xs text-slate-500">Item mengikuti template resmi dan tidak dapat ditambah atau dihapus petugas.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-700"><thead class="bg-slate-50 dark:bg-slate-800"><tr><th class="px-4 py-3 text-left">No</th><th class="px-4 py-3 text-left">Item Kebersihan</th><th class="px-4 py-3 text-left">Hasil</th><th class="px-4 py-3 text-left">Evaluasi jika tidak terpenuhi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach($relations['checklistItems'] ?? [] as $index=>$row)<tr wire:key="check-{{ $row['_id'] ?? $index }}"><td class="px-4 py-3">{{ $loop->iteration }}</td><td class="px-4 py-3 font-semibold">{{ $row['item_name'] }}</td><td class="px-4 py-3"><select wire:model="relations.checklistItems.{{ $index }}.result" @disabled(!$workEditable) class="{{ $input }} min-w-[170px]"><option value="pending">Belum diperiksa</option><option value="pass">Terpenuhi</option><option value="fail">Tidak terpenuhi</option></select></td><td class="px-4 py-3"><input wire:model="relations.checklistItems.{{ $index }}.notes" @disabled(!$workEditable) class="{{ $input }} min-w-[280px]" placeholder="Wajib jika tidak terpenuhi"></td></tr>@endforeach</tbody></table></div></section>

            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex justify-between gap-3"><div><h3 class="font-bold">Dokumentasi</h3><p class="mt-1 text-xs text-slate-500">Foto sebelum opsional. Minimal satu foto hasil wajib.</p></div>@if($workEditable)<button type="button" wire:click="addRelationRow('documentations')" class="h-9 rounded-xl bg-sky-600 px-4 text-xs font-bold text-white">+ Tambah foto</button>@endif</div><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($relations['documentations'] ?? [] as $index=>$row)<div class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="grid gap-3 sm:grid-cols-2"><select wire:model="relations.documentations.{{ $index }}.phase" @disabled(!$workEditable) class="{{ $input }}"><option value="before">Sebelum (opsional)</option><option value="after">Hasil kebersihan</option></select><input wire:model="relations.documentations.{{ $index }}.caption" @disabled(!$workEditable) class="{{ $input }}" placeholder="Keterangan"><input wire:model="uploads.documentations.{{ $index }}.photo_path" type="file" accept="image/*" @disabled(!$workEditable) class="sm:col-span-2 block w-full text-xs">@if($row['photo_path'] ?? null)<a target="_blank" href="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($row['photo_path']) }}" class="text-xs font-bold text-sky-600">Lihat foto tersimpan</a>@endif</div>@if($workEditable)<div class="mt-3 text-right"><button type="button" wire:click="removeRelationRow('documentations',{{ $index }})" class="text-xs font-bold text-rose-600">Hapus</button></div>@endif</div>@endforeach</div></section>

            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex justify-between gap-3"><div><h3 class="font-bold">Bahan pembersih</h3><p class="mt-1 text-xs text-slate-500">Opsional, isi hanya jika perlu dicatat.</p></div>@if($workEditable)<button type="button" wire:click="addRelationRow('chemicalUsages')" class="h-9 rounded-xl border border-slate-200 px-4 text-xs font-bold dark:border-slate-700">+ Tambah bahan</button>@endif</div><div class="mt-4 space-y-3">@foreach($relations['chemicalUsages'] ?? [] as $index=>$row)<div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-4 dark:border-slate-700"><input wire:model="relations.chemicalUsages.{{ $index }}.chemical_name" @disabled(!$workEditable) class="{{ $input }}" placeholder="Nama bahan"><input wire:model="relations.chemicalUsages.{{ $index }}.quantity" type="number" step="0.001" @disabled(!$workEditable) class="{{ $input }}" placeholder="Jumlah"><input wire:model="relations.chemicalUsages.{{ $index }}.unit" @disabled(!$workEditable) class="{{ $input }}" placeholder="Satuan"><input wire:model="relations.chemicalUsages.{{ $index }}.purpose" @disabled(!$workEditable) class="{{ $input }}" placeholder="Kegunaan">@if($workEditable)<button type="button" wire:click="removeRelationRow('chemicalUsages',{{ $index }})" class="text-left text-xs font-bold text-rose-600">Hapus</button>@endif</div>@endforeach</div></section>

            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex justify-between gap-3"><div><h3 class="font-bold">Temuan</h3><p class="mt-1 text-xs text-slate-500">Opsional. Temuan kritis wajib memiliki tindakan sementara.</p></div>@if($workEditable)<button type="button" wire:click="addRelationRow('findings')" class="h-9 rounded-xl border border-slate-200 px-4 text-xs font-bold dark:border-slate-700">+ Tambah temuan</button>@endif</div><div class="mt-4 space-y-3">@foreach($relations['findings'] ?? [] as $index=>$row)<div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-2 dark:border-slate-700"><input wire:model="relations.findings.{{ $index }}.category" @disabled(!$workEditable) class="{{ $input }}" placeholder="Kategori"><select wire:model="relations.findings.{{ $index }}.severity" @disabled(!$workEditable) class="{{ $input }}">@foreach(App\Enums\CleaningFindingSeverity::options() as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><textarea wire:model="relations.findings.{{ $index }}.description" rows="2" @disabled(!$workEditable) class="{{ $textarea }}" placeholder="Deskripsi temuan"></textarea><textarea wire:model="relations.findings.{{ $index }}.corrective_action" rows="2" @disabled(!$workEditable) class="{{ $textarea }}" placeholder="Tindakan sementara/koreksi"></textarea>@if($workEditable)<button type="button" wire:click="removeRelationRow('findings',{{ $index }})" class="text-left text-xs font-bold text-rose-600">Hapus temuan</button>@endif</div>@endforeach</div></section>

            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 class="font-bold">Limbah</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><label><span class="mb-1 block text-xs font-semibold">Apakah terdapat limbah?</span><select wire:model="data.waste_presence" @disabled(!$workEditable) class="{{ $input }}"><option value="">Pilih</option><option value="none">Tidak ada limbah</option><option value="yes">Ada limbah</option></select></label><div class="flex items-end">@if(($data['waste_presence'] ?? '')==='yes')@if($record?->wasteHandoverReport)<a wire:navigate href="{{ route('v3.waste-handovers.show',$record->wasteHandoverReport) }}" class="inline-flex h-10 items-center rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Buka berita acara limbah</a>@else<a wire:navigate href="{{ route('v3.waste-handovers.create',['division'=>'cleaning','source_type'=>'cleaning_session','source_id'=>$record?->id,'source_reference'=>$record?->session_number]) }}" class="inline-flex h-10 items-center rounded-xl bg-amber-500 px-4 text-xs font-bold text-white">Buat berita acara limbah</a>@endif @else<p class="text-xs text-slate-500">Pilih “Ada limbah” untuk membuat berita acara bersama.</p>@endif</div></div></section>

            @if($workEditable)<section class="sticky bottom-4 z-10 flex justify-end rounded-2xl border border-slate-200 bg-white/90 p-3 shadow-xl backdrop-blur dark:border-slate-700 dark:bg-slate-900/90"><button type="submit" class="h-10 rounded-xl bg-sky-600 px-5 text-xs font-bold text-white">Simpan progres</button></section>@endif
        </form>

        @if($record)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><label><span class="mb-1 block text-xs font-semibold">Catatan aksi/revisi</span><textarea wire:model="workflowNotes" rows="2" class="{{ $textarea }}"></textarea></label><div class="mt-4 flex flex-wrap justify-end gap-2">@foreach($actions as $action=>$label)@php($authorized=in_array($action,['verify','revision'],true)?$canApprove:($action==='submit'?$canSubmit:$canUpdate))@if($authorized)<button wire:click="workflow('{{ $action }}')" wire:confirm="Lanjutkan: {{ $label }}?" class="h-10 rounded-xl px-4 text-xs font-bold text-white {{ $action==='revision'?'bg-rose-600':($action==='submit'||$action==='verify'?'bg-emerald-600':'bg-slate-800') }}">{{ $label }}</button>@endif @endforeach</div></section>@endif
    </div>
</x-v3.shell>
