<x-v3.shell :$unit :$navigation :$roleLabel title="Rincian Pengadaan" eyebrow="Kontrol peran dan harga">
    <div class="mx-auto max-w-[1450px] space-y-5">
        <div class="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div><a wire:navigate href="{{ route('v3.procurement.index') }}" class="inline-flex items-center gap-2 text-xs font-bold text-sky-700"><x-v3.icon name="arrow-left" class="size-4" /> Kembali ke pengadaan</a><h2 class="mt-3 text-2xl font-bold tracking-tight text-slate-950">{{ $request->request_number }}</h2><p class="mt-1 text-sm text-slate-500">Dibutuhkan {{ $request->needed_date?->translatedFormat('d M Y') ?? 'tanpa tanggal' }} · {{ $request->total_items }} bahan</p></div><div class="flex flex-wrap gap-2">@if ($request->nutritionRequirementPlan)<a wire:navigate href="{{ route('v3.nutrition.requirements.show', $request->nutritionRequirementPlan) }}" class="inline-flex h-10 items-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600">Lihat kebutuhan asal</a>@endif @if ($request->status === \App\Models\ProcurementRequest::STATUS_ORDERED && (auth()->user()->is_super_admin || auth()->user()->can('stock.create')))<button wire:click="createReceipt" wire:confirm="Buat atau buka dokumen penerimaan bahan?" class="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Buat penerimaan</button>@endif</div></div>

        @if ($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror

        <section class="rounded-[26px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-7"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span class="rounded-full bg-cyan-300/10 px-3 py-1 text-[10px] font-bold text-cyan-200 ring-1 ring-cyan-300/20">{{ $statuses[$request->status] ?? '-' }}</span><h3 class="mt-4 text-2xl font-bold">Rp {{ number_format((float) $request->estimated_total_amount, 0, ',', '.') }}</h3><p class="mt-2 max-w-2xl text-sm text-slate-300">{{ $request->notes ?: 'Tanpa catatan permintaan.' }}</p></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Status harga</p><p class="mt-1 text-sm font-bold">{{ str($request->price_status)->replace('_', ' ')->title() }}</p></div><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Bahan</p><p class="mt-1 text-xl font-bold">{{ $request->total_items }}</p></div><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Pengaju</p><p class="mt-1 text-sm font-bold">{{ $request->submitter?->name ?? $request->creator?->name ?? '—' }}</p></div><div class="rounded-xl border border-cyan-300/20 bg-cyan-300/10 p-3"><p class="text-[10px] text-cyan-200/70">Supplier terisi</p><p class="mt-1 text-xl font-bold text-cyan-100">{{ $request->items->whereNotNull('supplier_id')->count() }}/{{ $request->items->count() }}</p></div></div></div></section>

        <div class="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]">
            <aside class="space-y-5">
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Informasi permintaan</p><div class="mt-4 space-y-4"><label class="block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Tanggal permintaan</span><input wire:model="requestDate" type="date" @disabled(! $canHeaderEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label class="block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Tanggal dibutuhkan</span><input wire:model="neededDate" type="date" @disabled(! $canHeaderEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label class="block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Catatan Ahli Gizi</span><textarea wire:model="notes" rows="3" @disabled(! $canHeaderEdit) class="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm disabled:opacity-60"></textarea></label>@if ($canHeaderEdit || $canSupplierEdit || $canPriceEdit)<button wire:click="save" class="h-10 w-full rounded-xl border border-slate-200 text-xs font-bold text-slate-700">Simpan perubahan</button>@endif</div></section>

                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Workflow</p><p class="mt-2 text-xs leading-5 text-slate-500">Pemisahan peran tetap diberlakukan. Pengaju tidak dapat menyetujui permintaan sendiri.</p><label class="mt-4 block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Catatan keputusan/revisi</span><textarea wire:model="decisionNotes" rows="3" class="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" placeholder="Wajib untuk permintaan revisi"></textarea></label><div class="mt-3 grid gap-2">
                    @if ($request->isEditable() && (auth()->user()->is_super_admin || auth()->user()->can('procurement.submit')))<button wire:click="submit" wire:confirm="Ajukan permintaan ini?" class="h-10 rounded-xl bg-[#081d3a] text-xs font-bold text-white">Ajukan permintaan</button>@endif
                    @if ($request->status === \App\Models\ProcurementRequest::STATUS_SUBMITTED && (auth()->user()->is_super_admin || auth()->user()->can('procurement.approve')))<button wire:click="verifyFinance" wire:confirm="Verifikasi supplier dan harga seluruh bahan?" class="h-10 rounded-xl bg-sky-600 text-xs font-bold text-white">Verifikasi Keuangan</button>@endif
                    @if ($request->status === \App\Models\ProcurementRequest::STATUS_FINANCE_VERIFIED && (auth()->user()->is_super_admin || auth()->user()->can('procurement.finalize_price')))<button wire:click="finalizePrice" wire:confirm="Tetapkan dan kunci harga final?" class="h-10 rounded-xl bg-emerald-600 text-xs font-bold text-white">Tetapkan harga final</button>@endif
                    @if (in_array($request->status, [\App\Models\ProcurementRequest::STATUS_SUBMITTED, \App\Models\ProcurementRequest::STATUS_FINANCE_VERIFIED], true) && (auth()->user()->is_super_admin || auth()->user()->can('procurement.approve') || auth()->user()->can('procurement.finalize_price')))<button wire:click="requestRevision" class="h-10 rounded-xl bg-rose-50 text-xs font-bold text-rose-700 ring-1 ring-rose-100">Minta revisi</button>@endif
                    @if ($request->status === \App\Models\ProcurementRequest::STATUS_APPROVED && (auth()->user()->is_super_admin || auth()->user()->can('procurement.order')))<button wire:click="markOrdered" wire:confirm="Tandai seluruh bahan sudah dipesan?" class="h-10 rounded-xl bg-violet-600 text-xs font-bold text-white">Tandai dipesan</button>@endif
                    @if ($request->isEditable() && (auth()->user()->is_super_admin || auth()->user()->can('procurement.delete')))<button wire:click="delete" wire:confirm="Hapus draft permintaan ini?" class="h-10 rounded-xl text-xs font-bold text-rose-700 hover:bg-rose-50">Hapus draft</button>@endif
                </div>@if ($request->finance_notes)<div class="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-700 ring-1 ring-amber-100"><strong>Catatan proses:</strong><br>{{ $request->finance_notes }}</div>@endif</section>
            </aside>

            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Item pembelian</p><h3 class="mt-1 text-lg font-bold text-slate-950">Supplier, kuantitas, dan harga</h3><p class="mt-1 text-xs text-slate-500">Kolom yang dapat diedit mengikuti role dan status dokumen saat ini.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left"><thead><tr class="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400"><th class="px-4 py-3.5">Bahan</th><th class="px-4 py-3.5">Supplier</th><th class="px-4 py-3.5 text-right">Jumlah</th><th class="px-4 py-3.5 text-right">Berat</th><th class="px-4 py-3.5 text-right">Harga/satuan</th><th class="px-4 py-3.5 text-right">Subtotal</th><th class="px-4 py-3.5">Catatan</th></tr></thead><tbody class="divide-y divide-slate-100">
                @foreach ($request->items as $item)
                    <tr class="align-top"><td class="px-4 py-4"><p class="text-sm font-bold text-slate-800">{{ $item->ingredient_name_snapshot }}</p><p class="mt-1 text-xs text-slate-400">{{ $item->ingredient_code_snapshot ?: 'Tanpa kode' }} · {{ $item->unit_snapshot }}</p></td><td class="px-4 py-4"><select wire:model="rows.{{ $item->id }}.supplier_id" @disabled(! $canSupplierEdit) class="h-10 w-52 rounded-xl border border-slate-200 bg-white px-3 text-xs disabled:opacity-60"><option value="">Pilih supplier</option>@foreach ($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></td><td class="px-4 py-4"><input wire:model="rows.{{ $item->id }}.requested_quantity" type="number" min="0.0001" step="0.0001" @disabled(! $canHeaderEdit) class="h-10 w-32 rounded-xl border border-slate-200 bg-white px-3 text-right text-sm disabled:opacity-60"><p class="mt-1 text-right text-[10px] text-slate-400">{{ $item->unit_snapshot }}</p></td><td class="px-4 py-4 text-right text-sm font-semibold text-slate-600">{{ number_format((float) $item->requested_quantity_kg, 3, ',', '.') }} kg</td><td class="px-4 py-4"><input wire:model="rows.{{ $item->id }}.estimated_unit_price" type="number" min="0" step="1" @disabled(! $canPriceEdit) class="h-10 w-40 rounded-xl border border-slate-200 bg-white px-3 text-right text-sm disabled:opacity-60"></td><td class="px-4 py-4 text-right text-sm font-bold text-slate-700">Rp {{ number_format((float) $item->estimated_total_price, 0, ',', '.') }}</td><td class="px-4 py-4"><textarea wire:model="rows.{{ $item->id }}.notes" rows="2" @disabled(! $canHeaderEdit) class="w-48 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs disabled:opacity-60"></textarea></td></tr>
                @endforeach
            </tbody></table></div></section>
        </div>
    </div>
</x-v3.shell>
