<!doctype html>
<html lang="id"><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#111827}h1{font-size:16px;margin:0 0 4px}.meta{line-height:1.6;margin-bottom:10px}.metrics{width:100%;border-collapse:collapse;margin-bottom:10px}.metrics td{border:1px solid #d1d5db;padding:5px}.label{font-weight:bold;background:#f3f4f6}table.data{width:100%;border-collapse:collapse}table.data th,table.data td{border:1px solid #9ca3af;padding:5px}table.data th{background:#e5e7eb}.num{text-align:right}.notes{margin-top:10px;border:1px solid #d1d5db;padding:7px}
</style></head><body>
<h1>Laporan Gizi Harian</h1><div class="meta"><strong>Unit:</strong> {{ $report->sppgUnit?->name }}<br><strong>Nomor:</strong> {{ $report->report_number }} &nbsp; <strong>Tanggal:</strong> {{ $report->report_date?->format('d-m-Y') }} &nbsp; <strong>Menu:</strong> {{ $report->menu?->name ?? '-' }}</div>
<table class="metrics"><tr><td class="label">Penerima Rencana</td><td>{{ $report->planned_beneficiaries }}</td><td class="label">Penerima Aktual</td><td>{{ $report->actual_beneficiaries }}</td><td class="label">Porsi Tersaji</td><td>{{ $report->served_portions }}</td></tr><tr><td class="label">Penerimaan</td><td>{{ $report->average_acceptance_percent }}%</td><td class="label">Sisa</td><td>{{ $report->average_waste_percent }}%</td><td class="label">Temuan Terbuka</td><td>{{ $report->open_findings_count }}</td></tr></table>
<table class="data"><thead><tr><th>No</th><th>Komponen</th><th>Satuan</th><th>Rencana/Porsi</th><th>Aktual/Porsi</th><th>Target/Porsi</th><th>Pencapaian</th><th>Total Rencana</th><th>Total Aktual</th></tr></thead><tbody>@foreach($report->components as $index=>$component)<tr><td class="num">{{ $index+1 }}</td><td>{{ $component->component_name_snapshot }}</td><td>{{ $component->unit_snapshot }}</td><td class="num">{{ $component->planned_per_portion }}</td><td class="num">{{ $component->actual_per_portion }}</td><td class="num">{{ $component->target_per_portion }}</td><td class="num">{{ $component->achievement_percent }}%</td><td class="num">{{ $component->planned_total }}</td><td class="num">{{ $component->actual_total }}</td></tr>@endforeach</tbody></table>
<div class="notes"><strong>Evaluasi Ahli Gizi:</strong><br>{{ $report->evaluation_notes ?: '-' }}</div><div class="notes"><strong>Rekomendasi:</strong><br>{{ $report->recommendations ?: '-' }}</div>
</body></html>
