<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    @foreach ($distribution['cards'] as $card)
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold text-slate-500 dark:text-slate-400">{{ $card['label'] }}</p><p class="mt-2 text-3xl font-bold tracking-[-.04em] text-slate-950 dark:text-slate-50">{{ number_format($card['value'], 0, ',', '.') }}</p></div><span class="grid size-10 place-items-center rounded-xl ring-1 {{ $toneClasses[$card['tone']] ?? $toneClasses['slate'] }}"><x-v3.icon :name="$card['icon']" class="size-5" /></span></div><p class="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">{{ $card['detail'] }}</p></article>
    @endforeach
</section>

<section class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">
    <div class="flex flex-col gap-3 border-b border-slate-200 px-5 py-5 dark:border-slate-800 sm:flex-row sm:items-end sm:justify-between sm:px-6"><div><p class="text-[10px] font-bold uppercase tracking-[.17em] text-sky-700 dark:text-sky-300">Distribusi</p><h3 class="mt-1 text-lg font-bold text-slate-950 dark:text-slate-50">Pelaksanaan rute</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Porsi, waktu perjalanan, kendaraan, dan status setiap rute.</p></div>@if(auth()->user()->is_super_admin || auth()->user()->can('distribution.view'))<a href="{{ $distribution['detail_url'] }}" wire:navigate class="inline-flex h-10 items-center gap-2 self-start rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 sm:self-auto">Buka modul Distribusi<x-v3.icon name="arrow-up-right" class="size-4" /></a>@endif</div>
    <div class="overflow-x-auto"><table class="w-full min-w-[1480px] text-left"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500 dark:bg-slate-900 dark:text-slate-400"><tr><th class="px-5 py-3">Rute / Menu</th><th class="px-4 py-3 text-right">Kecil</th><th class="px-4 py-3 text-right">Besar</th><th class="px-4 py-3 text-right">Total</th><th class="px-4 py-3">Berangkat</th><th class="px-4 py-3">Tujuan Selesai</th><th class="px-4 py-3">Kembali</th><th class="px-4 py-3">Petugas</th><th class="px-4 py-3">Driver</th><th class="px-4 py-3">Kendaraan</th><th class="px-4 py-3">Proses</th><th class="px-5 py-3">Laporan</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm dark:divide-slate-800">@forelse($distribution['rows'] as $row)<tr class="align-top hover:bg-slate-50/70 dark:hover:bg-slate-900/70"><td class="px-5 py-4"><p class="font-bold">{{ $row['route'] }}</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ $row['menu'] }}</p><p class="mt-1 text-[10px] text-slate-400">{{ $row['number'] }}</p></td><td class="px-4 py-4 text-right font-semibold">{{ number_format($row['small'],0,',','.') }}</td><td class="px-4 py-4 text-right font-semibold">{{ number_format($row['large'],0,',','.') }}</td><td class="px-4 py-4 text-right font-bold text-sky-700 dark:text-sky-300">{{ number_format($row['total'],0,',','.') }}</td><td class="px-4 py-4 text-xs font-semibold">{{ $row['departed_at'] }}</td><td class="px-4 py-4 text-xs font-semibold">{{ $row['destinations_completed_at'] }}</td><td class="px-4 py-4 text-xs font-semibold">{{ $row['returned_at'] }}</td><td class="px-4 py-4 text-xs">{{ $row['officer'] }}</td><td class="px-4 py-4 text-xs">{{ $row['driver'] }}</td><td class="px-4 py-4 text-xs">{{ $row['vehicle'] }}</td><td class="px-4 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ring-1 {{ $badgeClasses[$row['process_tone']] ?? $badgeClasses['slate'] }}">{{ $row['process_status'] }}</span></td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ring-1 {{ $badgeClasses[$row['report_tone']] ?? $badgeClasses['slate'] }}">{{ $row['report_status'] }}</span></td></tr>@empty<tr><td colspan="12" class="px-6 py-14 text-center"><p class="text-sm font-bold text-slate-700 dark:text-slate-200">Belum ada data Distribusi</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Tidak ditemukan rute pada {{ \Carbon\Carbon::parse($workDate)->translatedFormat('d F Y') }}.</p></td></tr>@endforelse</tbody></table></div>
</section>

@if(count($distribution['rows']))
<section class="space-y-4">
    <div><p class="text-[10px] font-bold uppercase tracking-[.17em] text-sky-700 dark:text-sky-300">Tujuan distribusi</p><h3 class="mt-1 text-lg font-bold text-slate-950 dark:text-slate-50">Tujuan langsung per rute</h3></div>
    @foreach($distribution['rows'] as $row)
        <article class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">
            <div class="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold text-slate-950 dark:text-slate-50">{{ $row['route'] }}</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ count($row['stops']) }} tujuan · {{ $row['menu'] }}</p></div>@if(array_sum($row['return_summary']) > 0)<div class="flex flex-wrap gap-2 text-[10px] font-bold text-slate-600 dark:text-slate-300"><span class="rounded-full bg-slate-100 px-2.5 py-1 dark:bg-slate-800">Porsi kembali {{ number_format($row['return_summary']['portions'],0,',','.') }}</span><span class="rounded-full bg-slate-100 px-2.5 py-1 dark:bg-slate-800">Ompreng {{ number_format($row['return_summary']['containers'],0,',','.') }}</span><span class="rounded-full bg-rose-50 px-2.5 py-1 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">Rusak {{ number_format($row['return_summary']['damaged'],0,',','.') }} · Hilang {{ number_format($row['return_summary']['lost'],0,',','.') }}</span></div>@endif</div>
            <div class="overflow-x-auto"><table class="w-full min-w-[1220px] text-left"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500 dark:bg-slate-900 dark:text-slate-400"><tr><th class="px-5 py-3">Urutan / Tujuan</th><th class="px-4 py-3">Jenis</th><th class="px-4 py-3">Porsi Kecil</th><th class="px-4 py-3">Porsi Besar</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Rencana / Tiba</th><th class="px-4 py-3">Penerima</th><th class="px-4 py-3">Status</th><th class="px-5 py-3 text-right">Foto</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm dark:divide-slate-800">@forelse($row['stops'] as $stop)<tr><td class="px-5 py-4"><p class="font-bold">{{ $stop['sequence'] }}. {{ $stop['destination'] }}</p></td><td class="px-4 py-4 text-xs">{{ $stop['type'] }}</td><td class="px-4 py-4"><p class="font-semibold">{{ number_format($stop['actual_small'] ?? $stop['planned_small'],0,',','.') }}</p>@if($stop['actual_small'] !== null && $stop['actual_small'] !== $stop['planned_small'])<p class="text-[10px] text-slate-400">Rencana {{ number_format($stop['planned_small'],0,',','.') }}</p>@endif</td><td class="px-4 py-4"><p class="font-semibold">{{ number_format($stop['actual_large'] ?? $stop['planned_large'],0,',','.') }}</p>@if($stop['actual_large'] !== null && $stop['actual_large'] !== $stop['planned_large'])<p class="text-[10px] text-slate-400">Rencana {{ number_format($stop['planned_large'],0,',','.') }}</p>@endif</td><td class="px-4 py-4"><p class="font-bold text-sky-700 dark:text-sky-300">{{ number_format($stop['actual_total'] ?? $stop['planned_total'],0,',','.') }}</p>@if($stop['actual_total'] !== null && $stop['actual_total'] !== $stop['planned_total'])<p class="text-[10px] text-slate-400">Rencana {{ number_format($stop['planned_total'],0,',','.') }}</p>@endif</td><td class="px-4 py-4 text-xs"><p>Rencana {{ $stop['planned_at'] }}</p><p class="mt-1">Tiba {{ $stop['arrived_at'] }}</p></td><td class="px-4 py-4 text-xs">{{ $stop['recipient'] }}</td><td class="px-4 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ring-1 {{ $badgeClasses[$stop['status_tone']] ?? $badgeClasses['slate'] }}">{{ $stop['status'] }}</span></td><td class="px-5 py-4 text-right">@if($stop['photo_url'])<x-v3.documentation-button :url="$stop['photo_url']" :title="'Serah terima · '.$stop['destination']" label="Lihat Foto" class="!px-2.5 !py-1.5" />@else<span class="text-xs text-slate-400">—</span>@endif</td></tr>@empty<tr><td colspan="9" class="px-6 py-8 text-center text-sm text-slate-500 dark:text-slate-400">Belum ada tujuan pada rute ini.</td></tr>@endforelse</tbody></table></div>
            @if(count($row['documentations']))<div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800"><p class="mb-3 text-xs font-bold text-slate-700 dark:text-slate-300">Dokumentasi Rute</p><div class="flex flex-wrap gap-2">@foreach($row['documentations'] as $documentation)<x-v3.documentation-button :url="$documentation['photo_url']" :title="$documentation['phase'].' · '.$documentation['caption'].' · '.$documentation['time']" :label="$documentation['phase']" class="!px-2.5 !py-1.5" />@endforeach</div></div>@endif
        </article>
    @endforeach
</section>
@endif
