<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    @foreach ($portioning['cards'] as $card)
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950">
            <div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-semibold text-slate-500 dark:text-slate-400">{{ $card['label'] }}</p><p class="mt-2 truncate text-3xl font-bold tracking-[-.04em] text-slate-950 dark:text-slate-50">{{ is_numeric($card['value']) ? number_format($card['value'], 0, ',', '.') : $card['value'] }}</p></div><span class="grid size-10 shrink-0 place-items-center rounded-xl ring-1 {{ $toneClasses[$card['tone']] ?? $toneClasses['slate'] }}"><x-v3.icon :name="$card['icon']" class="size-5" /></span></div>
            <p class="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">{{ $card['detail'] }}</p>
        </article>
    @endforeach
</section>

<section class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">
    <div class="flex flex-col gap-3 border-b border-slate-200 px-5 py-5 dark:border-slate-800 sm:flex-row sm:items-end sm:justify-between sm:px-6">
        <div><p class="text-[10px] font-bold uppercase tracking-[.17em] text-sky-700 dark:text-sky-300">Pemorsian</p><h3 class="mt-1 text-lg font-bold text-slate-950 dark:text-slate-50">Sesi dan realisasi porsi</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Target, hasil aktual, rute yang selesai, dan status laporan pada tanggal terpilih.</p></div>
        @if (auth()->user()->is_super_admin || auth()->user()->can('portioning.view'))<a href="{{ $portioning['detail_url'] }}" wire:navigate class="inline-flex h-10 items-center gap-2 self-start rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 sm:self-auto">Buka modul Pemorsian<x-v3.icon name="arrow-up-right" class="size-4" /></a>@endif
    </div>
    <div class="overflow-x-auto">
        <table class="w-full min-w-[1420px] text-left">
            <thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500 dark:bg-slate-900 dark:text-slate-400"><tr><th class="px-5 py-3">No / Menu</th><th class="px-4 py-3 text-right">Target Kecil</th><th class="px-4 py-3 text-right">Target Besar</th><th class="px-4 py-3 text-right">Target Total</th><th class="px-4 py-3 text-right">Aktual Kecil</th><th class="px-4 py-3 text-right">Aktual Besar</th><th class="px-4 py-3 text-right">Aktual Total</th><th class="px-4 py-3">Mulai / Selesai</th><th class="px-4 py-3">Petugas</th><th class="px-4 py-3">Proses</th><th class="px-4 py-3">Laporan</th><th class="px-5 py-3">Rute</th></tr></thead>
            <tbody class="divide-y divide-slate-100 text-sm dark:divide-slate-800">
                @forelse ($portioning['rows'] as $row)
                    <tr class="align-top transition hover:bg-slate-50/70 dark:hover:bg-slate-900/70">
                        <td class="px-5 py-4"><p class="font-bold text-slate-900 dark:text-slate-100">{{ $row['menu'] }}</p><p class="mt-1 text-[10px] text-slate-400">{{ $row['number'] }}</p></td>
                        <td class="px-4 py-4 text-right font-semibold">{{ number_format($row['target_small'], 0, ',', '.') }}</td><td class="px-4 py-4 text-right font-semibold">{{ number_format($row['target_large'], 0, ',', '.') }}</td><td class="px-4 py-4 text-right font-bold text-sky-700 dark:text-sky-300">{{ number_format($row['target_total'], 0, ',', '.') }}</td>
                        <td class="px-4 py-4 text-right font-semibold">{{ number_format($row['actual_small'], 0, ',', '.') }}</td><td class="px-4 py-4 text-right font-semibold">{{ number_format($row['actual_large'], 0, ',', '.') }}</td><td class="px-4 py-4 text-right font-bold text-emerald-700 dark:text-emerald-300">{{ number_format($row['actual_total'], 0, ',', '.') }}</td>
                        <td class="px-4 py-4 text-xs text-slate-600 dark:text-slate-300"><p>Mulai {{ $row['started_at'] }}</p><p class="mt-1">Selesai {{ $row['completed_at'] }}</p></td><td class="px-4 py-4 text-xs text-slate-600 dark:text-slate-300">{{ $row['officer'] }}</td>
                        <td class="px-4 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ring-1 {{ $badgeClasses[$row['process_tone']] ?? $badgeClasses['slate'] }}">{{ $row['process_status'] }}</span></td><td class="px-4 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ring-1 {{ $badgeClasses[$row['report_tone']] ?? $badgeClasses['slate'] }}">{{ $row['report_status'] }}</span></td>
                        <td class="px-5 py-4"><details><summary class="cursor-pointer text-xs font-bold text-sky-700 dark:text-sky-300">{{ count($row['route_records']) }} selesai · {{ count($row['allocations']) }} target</summary><div class="mt-3 w-[440px] max-w-[70vw] space-y-3">
                            <div><p class="mb-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">Target per rute</p>@forelse($row['allocations'] as $allocation)<div class="mb-1 rounded-xl bg-slate-50 p-2.5 text-[11px] dark:bg-slate-900"><b>{{ $allocation['route'] }}</b> · {{ $allocation['destination'] }}<br>{{ number_format($allocation['target_small'], 0, ',', '.') }} kecil · {{ number_format($allocation['target_large'], 0, ',', '.') }} besar · rencana {{ $allocation['planned_at'] }}</div>@empty<p class="text-xs text-slate-400">Belum ada alokasi rute.</p>@endforelse</div>
                            <div><p class="mb-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">Realisasi rute</p>@forelse($row['route_records'] as $record)<div class="mb-1 flex items-center justify-between gap-2 rounded-xl bg-slate-50 p-2.5 text-[11px] dark:bg-slate-900"><span><b>{{ $record['route'] }}</b><br>{{ number_format($record['actual_small'], 0, ',', '.') }} kecil · {{ number_format($record['actual_large'], 0, ',', '.') }} besar · {{ $record['completed_at'] }}</span>@if($record['photo_url'])<x-v3.documentation-button :url="$record['photo_url']" :title="'Dokumentasi Pemorsian · '.$record['route']" label="Foto" class="!px-2.5 !py-1.5" />@endif</div>@empty<p class="text-xs text-slate-400">Belum ada rute selesai.</p>@endforelse</div>
                        </div></details></td>
                    </tr>
                @empty
                    <tr><td colspan="12" class="px-6 py-14 text-center"><p class="text-sm font-bold text-slate-700 dark:text-slate-200">Belum ada data Pemorsian</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Tidak ditemukan sesi pada {{ \Carbon\Carbon::parse($workDate)->translatedFormat('d F Y') }}.</p></td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</section>

<section class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">
    <div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><h3 class="font-bold text-slate-950 dark:text-slate-50">Sisa Makanan</h3><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Jumlah tetap ditampilkan sesuai satuan aslinya dan tidak dijumlahkan lintas satuan.</p></div>
    <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500 dark:bg-slate-900 dark:text-slate-400"><tr><th class="px-5 py-3">Waktu</th><th class="px-4 py-3">Sesi</th><th class="px-4 py-3">Jenis Makanan</th><th class="px-4 py-3">Jumlah</th><th class="px-4 py-3">Catatan</th><th class="px-5 py-3 text-right">Foto</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm dark:divide-slate-800">@forelse($portioning['leftovers'] as $leftover)<tr><td class="px-5 py-4 text-xs font-semibold">{{ $leftover['time'] }}</td><td class="px-4 py-4 text-xs text-slate-500 dark:text-slate-400">{{ $leftover['session'] }}</td><td class="px-4 py-4 font-bold">{{ $leftover['food_type'] }}</td><td class="px-4 py-4 font-bold text-amber-700 dark:text-amber-300">{{ $leftover['quantity'] }}</td><td class="px-4 py-4 text-xs text-slate-600 dark:text-slate-300">{{ $leftover['notes'] }}</td><td class="px-5 py-4 text-right">@if($leftover['photo_url'])<x-v3.documentation-button :url="$leftover['photo_url']" :title="'Sisa makanan · '.$leftover['food_type']" label="Foto" class="!px-2.5 !py-1.5" />@else<span class="text-xs text-slate-400">—</span>@endif</td></tr>@empty<tr><td colspan="6" class="px-6 py-10 text-center text-sm text-slate-500 dark:text-slate-400">Tidak ada data sisa makanan pada tanggal ini.</td></tr>@endforelse</tbody></table></div>
</section>
