<x-v3.shell :$unit :$navigation :$roleLabel title="Rencana Lapangan" eyebrow="Rencana distribusi dan kebutuhan operasional">
    <div class="mx-auto max-w-[1450px] space-y-5">
        <x-v3.flash-alert />
        <x-v3.date-filter label="Tanggal rencana distribusi" />
        <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Lapangan</p><h2 class="mt-2 text-2xl font-bold text-slate-950">Rencana distribusi</h2><p class="mt-1 text-sm text-slate-500">Pilih menu aktif, muat jumlah penerima, konfirmasi rute, lalu aktifkan rencana. Dokumen tiap divisi dibuat manual pada modul masing-masing.</p></div>@if($canCreate)<a wire:navigate href="{{ route('v3.field.plans.create') }}" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-sky-600 px-5 text-sm font-bold text-white"><x-v3.icon name="plus" class="size-4" /> Buat rencana</a>@endif</div>
        <section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><input wire:model.live.debounce.300ms="search" type="search" placeholder="Cari nomor rencana..." class="h-11 w-full max-w-lg rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm"></section>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500">Rencana</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500">Distribusi</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500">Tujuan & porsi</th><th class="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500">Status</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($plans as $plan)<tr><td class="px-5 py-4"><p class="font-bold text-slate-900">{{ $plan->plan_number }}</p><p class="mt-1 text-xs text-slate-400">{{ $plan->menu_name_snapshot }}</p></td><td class="px-5 py-4 text-slate-600">{{ $plan->distribution_date?->translatedFormat('d M Y') }}</td><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ $plan->destination_count }} tujuan</p><p class="text-xs text-slate-400">{{ number_format($plan->planned_total_portions) }} porsi</p></td><td class="px-5 py-4"><span class="rounded-full bg-sky-50 px-2.5 py-1 text-[10px] font-bold text-sky-700">{{ $plan->status->label() }}</span></td><td class="px-5 py-4 text-right"><a wire:navigate href="{{ route('v3.field.plans.show', $plan) }}" class="text-xs font-bold text-sky-700">Buka rincian</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-sm text-slate-400">Belum ada rencana lapangan.</td></tr>@endforelse</tbody></table></div>@if($plans->hasPages())<div class="border-t border-slate-100 p-4">{{ $plans->links() }}</div>@endif</section>
    </div>
</x-v3.shell>
