<x-v3.shell :$unit :$navigation :$roleLabel title="Serah Bahan" eyebrow="Gudang → Persiapan">
    <div class="mx-auto max-w-[1450px] space-y-5">
        @if (session('v3.status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('v3.status') }}</div>@endif
        <section class="rounded-[28px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-7"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span class="rounded-full bg-amber-300/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-amber-200 ring-1 ring-amber-300/20">Peralihan tanggung jawab</span><h2 class="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Catat bahan keluar dan penerimaan Persiapan.</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Saat Gudang mengunci penyerahan, kartu stok otomatis berkurang. Tim Persiapan melanjutkan pemeriksaan kondisi, jumlah siap olah, dan catatan limbah pada dokumen yang sama.</p></div><a wire:navigate href="{{ route('v3.warehouse.stock.index') }}" class="inline-flex h-11 items-center rounded-xl border border-white/15 bg-white/10 px-4 text-xs font-bold text-white">Lihat kartu stok</a></div><div class="mt-6 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-white/10 bg-white/[.07] px-4 py-3"><p class="text-[10px] uppercase tracking-wider text-slate-400">Dokumen</p><p class="mt-1 text-xl font-bold">{{ $handoverCount }}</p></div><div class="rounded-2xl border border-amber-300/20 bg-amber-300/10 px-4 py-3"><p class="text-[10px] uppercase tracking-wider text-amber-200/70">Belum diterima penuh</p><p class="mt-1 text-xl font-bold text-amber-100">{{ $pendingCount }}</p></div><div class="rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-4 py-3"><p class="text-[10px] uppercase tracking-wider text-cyan-200/70">Siap olah</p><p class="mt-1 text-xl font-bold text-cyan-100">{{ $preparedCount }}</p></div></div></section>

        <div class="grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]">
            @if (auth()->user()->is_super_admin || auth()->user()->can('stock.create'))
                <form wire:submit="createFromReceipt" class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Dokumen baru</p><h3 class="mt-1 text-base font-bold text-slate-950">Ambil dari penerimaan stok</h3><p class="mt-2 text-xs leading-5 text-slate-500">Jika dokumen untuk penerimaan yang sama sudah ada, sistem akan membuka dokumen tersebut.</p><label class="mt-4 block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Penerimaan sudah masuk stok</span><select wire:model="receiptId" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih penerimaan</option>@foreach ($receivedReceipts as $receipt)<option value="{{ $receipt->id }}">{{ $receipt->receipt_number }} — {{ $receipt->receipt_date?->format('d/m/Y') }}</option>@endforeach</select>@error('receiptId')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><button type="submit" @disabled($receivedReceipts->isEmpty()) class="mt-4 h-11 w-full rounded-xl bg-[#081d3a] text-xs font-bold text-white disabled:opacity-50">Buat / buka dokumen</button></form>
            @else
                <section class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-800">Akses proses Persiapan</p><p class="mt-1 text-xs leading-5 text-slate-500">Dokumen dibuat oleh Gudang; tim Persiapan melanjutkan proses pada rincian dokumen.</p></section>
            @endif
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:p-5"><div class="relative flex-1"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-11 place-items-center text-slate-400"><x-v3.icon name="search" class="size-[18px]" /></span><input wire:model.live.debounce.350ms="search" type="search" placeholder="Cari nomor, petugas, atau bahan..." class="h-11 w-full rounded-xl border border-slate-200 bg-slate-50/50 pl-11 pr-4 text-sm"></div><select wire:model.live="status" class="h-11 min-w-56 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-600"><option value="all">Semua status</option>@foreach ($statuses as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left"><thead><tr class="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400"><th class="px-5 py-3.5">Dokumen</th><th class="px-5 py-3.5">Gudang</th><th class="px-5 py-3.5">Persiapan</th><th class="px-5 py-3.5 text-center">Item</th><th class="px-5 py-3.5">Status</th><th class="px-5 py-3.5 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($handovers as $handover)<tr class="hover:bg-sky-50/30"><td class="px-5 py-4"><p class="text-sm font-bold text-slate-800">{{ $handover->handover_number }}</p><p class="mt-0.5 text-xs text-slate-400">{{ $handover->handover_date?->translatedFormat('d M Y') }}</p></td><td class="px-5 py-4 text-sm text-slate-600">{{ $handover->warehouse_officer_name ?: '—' }}</td><td class="px-5 py-4 text-sm text-slate-600">{{ $handover->preparation_officer_name ?: '—' }}</td><td class="px-5 py-4 text-center text-sm font-bold text-slate-700">{{ $handover->items->count() }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 ring-1 ring-slate-200">{{ $statuses[$handover->status] ?? '-' }}</span></td><td class="px-5 py-4 text-right"><a wire:navigate href="{{ route('v3.warehouse.handovers.show', $handover) }}" class="rounded-lg bg-sky-50 px-3 py-2 text-[10px] font-bold text-sky-700 ring-1 ring-sky-100">Buka</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-16 text-center"><p class="text-sm font-bold text-slate-700">Belum ada serah bahan</p><p class="mt-1 text-xs text-slate-400">Buat dari penerimaan yang sudah masuk stok.</p></td></tr>@endforelse</tbody></table></div>@if ($handovers->hasPages())<div class="border-t border-slate-100 px-5 py-4">{{ $handovers->links() }}</div>@endif</section>
        </div>
    </div>
</x-v3.shell>
