<x-v3.shell :$unit :$navigation :$roleLabel title="Rincian Serah Bahan" eyebrow="Gudang dan Persiapan pada satu dokumen">
    <div class="mx-auto max-w-[1450px] space-y-5">
        <div class="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div><a wire:navigate href="{{ route('v3.warehouse.handovers.index') }}" class="inline-flex items-center gap-2 text-xs font-bold text-sky-700"><x-v3.icon name="arrow-left" class="size-4" /> Kembali ke serah bahan</a><h2 class="mt-3 text-2xl font-bold tracking-tight text-slate-950">{{ $handover->handover_number }}</h2><p class="mt-1 text-sm text-slate-500">{{ $handover->handover_date?->translatedFormat('d M Y') }} · {{ $handover->items->count() }} bahan</p></div><div class="flex flex-wrap gap-2">@if ((auth()->user()->is_super_admin || auth()->user()->can('preparation.export')) && $handover->status !== \App\Models\PreparationMaterialHandover::STATUS_DRAFT)<a href="{{ route('preparation.material-handovers.calculation-pdf', $handover) }}" target="_blank" class="inline-flex h-10 items-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600">BA Perhitungan</a>@endif @if ((auth()->user()->is_super_admin || auth()->user()->can('preparation.export')) && in_array($handover->status, [\App\Models\PreparationMaterialHandover::STATUS_WASTE_RECORDED, \App\Models\PreparationMaterialHandover::STATUS_HANDED_OVER_TO_PROCESSING, \App\Models\PreparationMaterialHandover::STATUS_COMPLETED], true))<a href="{{ route('preparation.material-handovers.waste-pdf', $handover) }}" target="_blank" class="inline-flex h-10 items-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600">BA Limbah</a>@endif</div></div>
        @if ($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror

        <section class="rounded-[26px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-7"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span class="rounded-full bg-amber-300/10 px-3 py-1 text-[10px] font-bold text-amber-200 ring-1 ring-amber-300/20">{{ $statuses[$handover->status] ?? '-' }}</span><h3 class="mt-4 text-2xl font-bold">{{ $handover->warehouse_officer_name ?: 'Petugas Gudang belum diisi' }}</h3><p class="mt-2 max-w-2xl text-sm text-slate-300">{{ $handover->notes ?: 'Tanpa catatan umum.' }}</p></div><div class="grid grid-cols-3 gap-3"><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Diserahkan</p><p class="mt-1 text-lg font-bold">{{ number_format((float) $handover->items->sum('handed_over_quantity_kg'), 2, ',', '.') }} kg</p></div><div class="rounded-xl border border-cyan-300/20 bg-cyan-300/10 p-3"><p class="text-[10px] text-cyan-200/70">Baik</p><p class="mt-1 text-lg font-bold text-cyan-100">{{ number_format((float) $handover->items->sum('good_quantity'), 2, ',', '.') }}</p></div><div class="rounded-xl border border-rose-300/20 bg-rose-300/10 p-3"><p class="text-[10px] text-rose-200/70">Rusak</p><p class="mt-1 text-lg font-bold text-rose-100">{{ number_format((float) $handover->items->sum('damaged_quantity'), 2, ',', '.') }}</p></div></div></div></section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Tanggal</span><input wire:model="handoverDate" type="date" @disabled(! $canWarehouseEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Petugas Gudang</span><input wire:model="warehouseOfficerName" type="text" @disabled(! $canWarehouseEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Petugas Persiapan</span><input wire:model="preparationOfficerName" type="text" @disabled(! $canPreparationEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label class="sm:col-span-2"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Catatan umum</span><input wire:model="notes" type="text" @disabled(! $canWarehouseEdit && ! $canPreparationEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label></div></section>

        <section class="space-y-3">
            @foreach ($handover->items as $item)
                <details @if($loop->first) open @endif class="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><summary class="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><h3 class="text-base font-bold text-slate-950">{{ $item->ingredient_name_snapshot }}</h3><p class="mt-1 text-xs text-slate-400">Kebutuhan {{ number_format((float) $item->requested_quantity, 4, ',', '.') }} {{ $item->unit_snapshot }} · Diserahkan {{ number_format((float) $item->handed_over_quantity_kg, 3, ',', '.') }} kg</p></div><div class="flex items-center gap-3"><span class="hidden rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 sm:inline-flex">{{ $item->supplier_batch_number ?: 'Tanpa batch' }}</span><x-v3.icon name="chevron-down" class="size-4 text-slate-400 transition group-open:rotate-180" /></div></summary><div class="border-t border-slate-100 p-5">
                    <div class="grid gap-5 xl:grid-cols-2">
                        <div><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Data penyerahan Gudang</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Diserahkan ({{ $item->unit_snapshot }})</span><input wire:model="rows.{{ $item->id }}.handed_over_quantity" type="number" min="0" step="0.0001" @disabled(! $canWarehouseEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Estimasi berat (kg)</span><input wire:model="rows.{{ $item->id }}.handed_over_quantity_kg" type="number" min="0" step="0.0001" @disabled(! $canWarehouseEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Batch supplier</span><input wire:model="rows.{{ $item->id }}.supplier_batch_number" type="text" @disabled(! $canWarehouseEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Kedaluwarsa</span><input wire:model="rows.{{ $item->id }}.expired_date" type="date" @disabled(! $canWarehouseEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div></div>
                        <div><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Pemeriksaan Persiapan</p><div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Diterima</span><input wire:model="rows.{{ $item->id }}.received_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Baik</span><input wire:model="rows.{{ $item->id }}.good_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Sedang</span><input wire:model="rows.{{ $item->id }}.moderate_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Rusak</span><input wire:model="rows.{{ $item->id }}.damaged_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div><label class="mt-3 block"><span class="mb-1 block text-[11px] font-semibold text-slate-500">Keterangan pemeriksaan</span><input wire:model="rows.{{ $item->id }}.inspection_notes" type="text" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>@if ($item->inspection_photo_url)<a href="{{ $item->inspection_photo_url }}" target="_blank" class="mt-2 inline-flex text-xs font-bold text-sky-700">Lihat bukti pemeriksaan</a>@endif</div>
                    </div>
                    <div class="mt-5 grid gap-5 border-t border-slate-100 pt-5 xl:grid-cols-2"><div><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Hasil persiapan</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Jumlah siap olah</span><input wire:model="rows.{{ $item->id }}.prepared_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Catatan pembersihan/pemotongan</span><input wire:model="rows.{{ $item->id }}.preparation_notes" type="text" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div></div><div><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Limbah persiapan</p><div class="mt-3 grid gap-3 sm:grid-cols-3"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Jenis limbah</span><input wire:model="rows.{{ $item->id }}.waste_type" type="text" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Jumlah</span><input wire:model="rows.{{ $item->id }}.waste_quantity" type="number" min="0" step="0.0001" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Satuan</span><input wire:model="rows.{{ $item->id }}.waste_unit_snapshot" type="text" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div><label class="mt-3 block"><span class="mb-1 block text-[11px] font-semibold text-slate-500">Catatan limbah</span><input wire:model="rows.{{ $item->id }}.waste_notes" type="text" @disabled(! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div></div>
                    <label class="mt-4 block"><span class="mb-1 block text-[11px] font-semibold text-slate-500">Catatan bahan</span><input wire:model="rows.{{ $item->id }}.notes" type="text" @disabled(! $canWarehouseEdit && ! $canPreparationEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>
                </div></details>
            @endforeach
        </section>

        @if ($canWarehouseEdit || $canPreparationEdit || $handover->status === \App\Models\PreparationMaterialHandover::STATUS_HANDED_OVER)
            <div class="sticky bottom-4 z-10 flex flex-wrap justify-end gap-2 rounded-2xl border border-slate-200 bg-white/90 p-3 shadow-xl backdrop-blur">
                @if ($canWarehouseEdit)<button wire:click="delete" wire:confirm="Hapus draft serah bahan ini?" class="h-10 rounded-xl px-4 text-xs font-bold text-rose-700 hover:bg-rose-50">Hapus draft</button>@endif
                @if ($canWarehouseEdit || $canPreparationEdit)<button wire:click="save" class="h-10 rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-700">Simpan perubahan</button>@endif
                @if ($handover->status === \App\Models\PreparationMaterialHandover::STATUS_DRAFT && (auth()->user()->is_super_admin || auth()->user()->can('stock.create')))<button wire:click="markHandedOver" wire:confirm="Kunci penyerahan dan kurangi kartu stok?" class="h-10 rounded-xl bg-amber-500 px-4 text-xs font-bold text-white">Serahkan dari Gudang</button>@endif
                @if ($handover->status === \App\Models\PreparationMaterialHandover::STATUS_HANDED_OVER && (auth()->user()->is_super_admin || auth()->user()->can('preparation.update')))<button wire:click="markReceived" wire:confirm="Konfirmasi bahan diterima Persiapan?" class="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Terima oleh Persiapan</button>@endif
                @if (in_array($handover->status, [\App\Models\PreparationMaterialHandover::STATUS_RECEIVED, \App\Models\PreparationMaterialHandover::STATUS_INSPECTED], true) && (auth()->user()->is_super_admin || auth()->user()->can('preparation.update')))<button wire:click="markInspected" class="h-10 rounded-xl bg-sky-600 px-4 text-xs font-bold text-white">Simpan pemeriksaan</button>@endif
                @if (in_array($handover->status, [\App\Models\PreparationMaterialHandover::STATUS_INSPECTED, \App\Models\PreparationMaterialHandover::STATUS_PREPARED], true) && (auth()->user()->is_super_admin || auth()->user()->can('preparation.update')))<button wire:click="markPrepared" class="h-10 rounded-xl bg-violet-600 px-4 text-xs font-bold text-white">Tandai siap olah</button>@endif
                @if (in_array($handover->status, [\App\Models\PreparationMaterialHandover::STATUS_PREPARED, \App\Models\PreparationMaterialHandover::STATUS_WASTE_RECORDED], true) && (auth()->user()->is_super_admin || auth()->user()->can('preparation.update')))<button wire:click="markWasteRecorded" class="h-10 rounded-xl bg-slate-700 px-4 text-xs font-bold text-white">Simpan catatan limbah</button>@endif
            </div>
        @endif
    </div>
</x-v3.shell>
