<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><style>
@page{margin:14mm 14mm 12mm}body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#111}.header{width:100%;border-collapse:collapse}.header td{border:1px solid #222;padding:5px;text-align:center}.logo{width:60px}.title{font-size:12px;font-weight:bold}.meta{font-size:9px;text-align:left!important}.party{margin-top:14px;line-height:1.7}.items{width:100%;border-collapse:collapse;margin-top:8px}.items th,.items td{border:1px solid #222;padding:6px}.items th{background:#dce6f4;text-align:center}.sign{width:100%;border-collapse:collapse;margin-top:14px}.sign td{border:1px solid #222;height:95px;text-align:center;vertical-align:bottom;padding:6px}.page-break{page-break-before:always}.signature-page{margin-top:20px}.center{text-align:center}.statement{margin:10px 0}.small{font-size:8px}
</style></head><body>
<table class="header"><tr><td rowspan="3" style="width:85px"><img class="logo" src="{{ public_path('images/logo-bgn.png') }}"><br><span class="small">Badan Gizi<br>Nasional</span></td><td class="title">{{ strtoupper($report->sppgUnit?->name ?? 'SPPG') }}</td><td class="meta">No. Dokumen : {{ $report->report_number }}</td></tr><tr><td><strong>FORM</strong></td><td class="meta">Revisi : {{ $report->document_revision ?: '00' }}</td></tr><tr><td class="title">BERITA ACARA SERAH TERIMA<br>LIMBAH SISA BAHAN MAKANAN</td><td class="meta">Tanggal Berlaku : {{ $report->effective_date?->translatedFormat('d F Y') ?? '-' }}</td></tr></table>
<div class="party">Kami yang bertanda tangan di bawah ini, pada hari ini <strong>{{ $report->handed_over_at?->translatedFormat('l') }}</strong>, tanggal <strong>{{ $report->handed_over_at?->translatedFormat('d F Y') }}</strong>:<br><br><strong>Nama</strong> : {{ $report->first_party_name }}<br><strong>Jabatan</strong> : {{ $report->first_party_position }}<br><strong>Alamat</strong> : {{ $report->first_party_address }}<br>Selanjutnya disebut <strong>PIHAK PERTAMA</strong><br><br><strong>Nama</strong> : {{ $report->second_party_name }}<br><strong>Jabatan</strong> : {{ $report->second_party_position }}<br><strong>Alamat</strong> : {{ $report->second_party_address }}<br>Selanjutnya disebut <strong>PIHAK KEDUA</strong></div>
<p class="statement"><strong>PIHAK PERTAMA</strong> menyerahkan limbah kepada <strong>PIHAK KEDUA</strong> dan <strong>PIHAK KEDUA</strong> menyatakan telah menerima limbah dari <strong>PIHAK PERTAMA</strong> berupa daftar terlampir:</p>
<table class="items"><thead><tr><th style="width:35px">NO</th><th>JENIS LIMBAH</th><th style="width:150px">BERAT/JUMLAH<br><span class="small">(koli, kg, atau satuan aktual)</span></th><th>CATATAN</th></tr></thead><tbody>@foreach($report->items as $item)<tr><td class="center">{{ $loop->iteration }}.</td><td>{{ $item->waste_type }}</td><td class="center">{{ number_format((float)$item->quantity,3,',','.') }} {{ $item->unit }}</td><td>{{ $item->notes }}</td></tr>@endforeach @for($i=$report->items->count();$i<3;$i++)<tr><td>{{ $i+1 }}.</td><td>&nbsp;</td><td></td><td></td></tr>@endfor</tbody></table>
<p>Demikianlah berita acara serah terima limbah ini dibuat oleh kedua belah pihak. Sejak penandatanganan berita acara ini, limbah tersebut menjadi tanggung jawab <strong>PIHAK KEDUA</strong>.</p><p class="center"><strong>MENYETUJUI,</strong></p><table class="sign"><tr><td>PIHAK PERTAMA</td><td>PIHAK KEDUA</td></tr></table>
<div class="page-break signature-page"><table class="header"><tr><td rowspan="3" style="width:85px"><img class="logo" src="{{ public_path('images/logo-bgn.png') }}"></td><td class="title">{{ strtoupper($report->sppgUnit?->name ?? 'SPPG') }}</td><td class="meta">No. Dokumen : {{ $report->report_number }}</td></tr><tr><td><strong>FORM</strong></td><td class="meta">Revisi : {{ $report->document_revision ?: '00' }}</td></tr><tr><td class="title">BERITA ACARA SERAH TERIMA<br>LIMBAH SISA BAHAN MAKANAN</td><td class="meta">Tanggal Berlaku : {{ $report->effective_date?->translatedFormat('d F Y') ?? '-' }}</td></tr></table><table class="sign" style="margin-top:35px"><tr><td>(.............................................................)<br><strong>{{ $report->first_party_name }}</strong><br>PIHAK PERTAMA</td><td>(.............................................................)<br><strong>{{ $report->second_party_name }}</strong><br>PIHAK KEDUA</td></tr></table></div>
</body></html>
