<x-v3.shell :$unit :$navigation :$roleLabel :title="$record ? 'Berita Acara Limbah' : 'Buat Berita Acara Limbah'" eyebrow="Format bersama tiga divisi">
    @php($input='h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950 disabled:opacity-60')
    @php($textarea='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950 disabled:opacity-60')
    <div class="mx-auto max-w-[1200px] space-y-5 text-slate-900 dark:text-slate-100">
        <x-v3.flash-alert />
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900">
            <div class="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-sky-600">Berita acara serah terima</p><h2 class="mt-1 text-xl font-bold">Limbah Sisa Bahan Makanan</h2>@if($record)<p class="mt-1 text-xs text-slate-500">{{ $record->report_number }} · {{ $record->status->label() }}</p>@endif</div>@if($record)<a target="_blank" href="{{ route('v3.waste-handovers.pdf', $record) }}" class="inline-flex h-10 items-center rounded-xl border border-slate-200 px-4 text-xs font-bold dark:border-slate-700">Ekspor PDF</a>@endif</div>
            <div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <label><span class="mb-1 block text-xs font-semibold">Divisi sumber</span><select wire:model="data.division_type" @disabled(!$editable || $record) class="{{ $input }}">@foreach($divisionOptions as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label>
                <label><span class="mb-1 block text-xs font-semibold">Tanggal dokumen</span><input wire:model="data.report_date" type="date" @disabled(!$editable) class="{{ $input }}"></label>
                <label><span class="mb-1 block text-xs font-semibold">Waktu serah-terima</span><input wire:model="data.handed_over_at" type="datetime-local" @disabled(!$editable) class="{{ $input }}"></label>
                <label><span class="mb-1 block text-xs font-semibold">Revisi dokumen</span><input wire:model="data.document_revision" @disabled(!$editable) class="{{ $input }}"></label>
                <label><span class="mb-1 block text-xs font-semibold">Tanggal berlaku</span><input wire:model="data.effective_date" type="date" @disabled(!$editable) class="{{ $input }}"></label>
                <label class="md:col-span-2"><span class="mb-1 block text-xs font-semibold">Referensi sumber</span><input wire:model="data.source_reference" @disabled(!$editable) class="{{ $input }}" placeholder="Nomor sesi Persiapan/Pencucian/Kebersihan"></label>
            </div>
        </section>
        <section class="grid gap-5 lg:grid-cols-2">
            <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 class="font-bold">Pihak Pertama</h3><div class="mt-4 space-y-3"><label><span class="mb-1 block text-xs font-semibold">Nama</span><input wire:model="data.first_party_name" @disabled(!$editable) class="{{ $input }}"></label><label><span class="mb-1 block text-xs font-semibold">Jabatan</span><input wire:model="data.first_party_position" @disabled(!$editable) class="{{ $input }}"></label><label><span class="mb-1 block text-xs font-semibold">Alamat</span><textarea wire:model="data.first_party_address" rows="3" @disabled(!$editable) class="{{ $textarea }}"></textarea></label></div></div>
            <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><h3 class="font-bold">Pihak Kedua</h3><div class="mt-4 space-y-3"><label><span class="mb-1 block text-xs font-semibold">Nama</span><input wire:model="data.second_party_name" @disabled(!$editable) class="{{ $input }}"></label><label><span class="mb-1 block text-xs font-semibold">Jabatan</span><input wire:model="data.second_party_position" @disabled(!$editable) class="{{ $input }}"></label><label><span class="mb-1 block text-xs font-semibold">Alamat</span><textarea wire:model="data.second_party_address" rows="3" @disabled(!$editable) class="{{ $textarea }}"></textarea></label></div></div>
        </section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h3 class="font-bold">Daftar Limbah</h3><p class="text-xs text-slate-500">Satuan dapat berupa kg, koli, karung, wadah, liter, atau satuan aktual lainnya.</p></div>@if($editable)<button type="button" wire:click="addItem" class="h-9 rounded-xl bg-sky-600 px-4 text-xs font-bold text-white">+ Tambah item</button>@endif</div><div class="mt-4 space-y-3">@foreach($items as $index=>$item)<div wire:key="waste-{{ $index }}" class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[1.4fr_.6fr_.6fr_1.2fr_auto] dark:border-slate-700"><input wire:model="items.{{ $index }}.waste_type" @disabled(!$editable) class="{{ $input }}" placeholder="Jenis limbah"><input wire:model="items.{{ $index }}.quantity" type="number" step="0.001" min="0" @disabled(!$editable) class="{{ $input }}" placeholder="Jumlah"><input wire:model="items.{{ $index }}.unit" @disabled(!$editable) class="{{ $input }}" placeholder="Satuan"><input wire:model="items.{{ $index }}.notes" @disabled(!$editable) class="{{ $input }}" placeholder="Catatan">@if($editable)<button type="button" wire:click="removeItem({{ $index }})" class="text-xs font-bold text-rose-600">Hapus</button>@endif<div class="md:col-span-5"><input wire:model="uploads.{{ $index }}.photo" type="file" accept="image/*" @disabled(!$editable) class="block w-full text-xs">@if($item['photo_path'] ?? null)<x-v3.documentation-button :url="\Illuminate\Support\Facades\Storage::disk('public')->url($item['photo_path'])" :title="'Foto limbah · '.($item['waste_type'] ?: 'Item '.($index + 1))" label="Lihat foto" class="mt-2" />@endif</div></div>@endforeach</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><label><span class="mb-1 block text-xs font-semibold">Catatan umum</span><textarea wire:model="data.notes" rows="3" @disabled(!$editable) class="{{ $textarea }}"></textarea></label>@if($editable)<div class="mt-4 flex justify-end gap-2">@if($record)<button wire:click="delete" wire:confirm="Hapus berita acara ini?" class="h-10 px-4 text-xs font-bold text-rose-600">Hapus</button>@endif<button wire:click="save" class="h-10 rounded-xl bg-sky-600 px-5 text-xs font-bold text-white">Simpan</button></div>@endif</section>
        @if($record)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><label><span class="mb-1 block text-xs font-semibold">Catatan pengajuan/revisi</span><textarea wire:model="workflowNotes" rows="2" class="{{ $textarea }}"></textarea></label><div class="mt-4 flex flex-wrap justify-end gap-2">@if($canSubmit)<button wire:click="submit" wire:confirm="Ajukan berita acara ini?" class="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">{{ $record->status === App\Enums\OperationalReportStatus::RevisionRequired ? 'Ajukan kembali' : 'Ajukan' }}</button>@endif @if($canReview)<button wire:click="requestRevision" class="h-10 rounded-xl bg-rose-600 px-4 text-xs font-bold text-white">Minta revisi</button><button wire:click="verify" class="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Setujui</button>@endif</div></section>@endif
    </div>
</x-v3.shell>
