<x-v3.shell :$unit :$navigation :$roleLabel title="Referensi Gizi & Bahan" eyebrow="Sumber perhitungan">
    <div class="mx-auto max-w-[1500px] space-y-5">
        <section class="rounded-[26px] bg-gradient-to-br from-[#081d3a] to-[#103765] p-6 text-white shadow-xl sm:p-7">
            <span class="rounded-full bg-cyan-300/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-cyan-200 ring-1 ring-cyan-300/20">Referensi spreadsheet</span>
            <h2 class="mt-5 text-3xl font-bold">Satu sumber untuk resep dan perhitungan.</h2>
            <p class="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Standar porsi bahan mengikuti sheet Standar Gizi siswa. Nilai gizi, BDD, susut, harga, satuan pembelian, dan pembulatan mengikuti DAFTAR BAHAN.</p>
        </section>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="flex gap-1 overflow-x-auto border-b border-slate-100 p-2">
                @foreach (['nutrition'=>['Standar gizi',$nutritionStandards->count()],'portions'=>['Standar porsi',$portionStandards->count()],'ingredients'=>['Master bahan',$ingredients->count()],'units'=>['Satuan',$measurementUnits->count()]] as $key=>[$label,$count])
                    <button wire:click="selectTab('{{ $key }}')" @class(['whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-bold','bg-[#081d3a] text-white'=>$tab===$key,'text-slate-500 hover:bg-slate-50'=>$tab!==$key])>{{ $label }} <span class="ml-1 opacity-60">{{ $count }}</span></button>
                @endforeach
            </div>

            <div class="overflow-x-auto">
                @if ($tab === 'ingredients')
                    <table class="w-full min-w-[1200px] text-left"><thead><tr class="bg-slate-50 text-[10px] font-bold uppercase text-slate-400"><th class="px-5 py-3.5">Bahan</th><th class="px-5 py-3.5">Kategori</th><th class="px-5 py-3.5">Satuan beli</th><th class="px-5 py-3.5 text-right">Harga</th><th class="px-5 py-3.5 text-right">BDD</th><th class="px-5 py-3.5 text-right">Susut</th><th class="px-5 py-3.5 text-right">Pembulatan</th><th class="px-5 py-3.5">Sumber</th><th class="px-5 py-3.5">Spesifikasi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($ingredients as $ingredient)<tr><td class="px-5 py-4"><p class="text-sm font-bold text-slate-800">{{ $ingredient->name }}</p><p class="text-xs text-slate-400">{{ $ingredient->code }}</p></td><td class="px-5 py-4 text-xs text-slate-600">{{ str($ingredient->category)->replace('_',' ')->title() }}</td><td class="px-5 py-4 text-sm">{{ $ingredient->measurementUnit?->symbol ?? '—' }}</td><td class="px-5 py-4 text-right text-sm">{{ $ingredient->reference_price !== null ? 'Rp '.number_format((float)$ingredient->reference_price,0,',','.') : '—' }}</td><td class="px-5 py-4 text-right text-sm">{{ number_format((float)$ingredient->edible_portion_percent,1,',','.') }}%</td><td class="px-5 py-4 text-right text-sm">× {{ number_format((float)$ingredient->loss_factor,2,',','.') }}</td><td class="px-5 py-4 text-right text-sm">{{ $ingredient->rounding_increment ?: '—' }}</td><td class="px-5 py-4 text-xs text-slate-500">{{ $ingredient->nutrition_source ?: '—' }}</td><td class="max-w-72 px-5 py-4 text-xs text-slate-500">{{ str($ingredient->specification ?: '—')->limit(100) }}</td></tr>@empty<tr><td colspan="9" class="p-14 text-center text-sm text-slate-500">Belum ada bahan.</td></tr>@endforelse</tbody></table>
                @elseif ($tab === 'nutrition')
                    <div class="border-b border-slate-100 px-5 py-3 text-xs text-slate-500">Nilai ditampilkan sebagai kebutuhan satu hari penuh (100% AKG).</div>
                    <table class="w-full min-w-[850px] text-left"><thead><tr class="bg-slate-50 text-[10px] font-bold uppercase text-slate-400"><th class="px-5 py-3.5">Kategori</th><th class="px-5 py-3.5">Komponen</th><th class="px-5 py-3.5">Usia</th><th class="px-5 py-3.5 text-right">Minimum harian</th><th class="px-5 py-3.5 text-right">Kebutuhan harian</th><th class="px-5 py-3.5 text-right">Maksimum harian</th><th class="px-5 py-3.5">Berlaku</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($nutritionStandards as $standard)<tr><td class="px-5 py-4 text-sm font-bold">{{ $standard->category?->name ?? '—' }}</td><td class="px-5 py-4 text-sm">{{ $standard->component?->name ?? '—' }}</td><td class="px-5 py-4 text-xs">{{ $standard->getAgeRangeLabel() }}</td><td class="px-5 py-4 text-right text-sm">{{ $standard->minimum_value !== null ? number_format((float) $standard->minimum_value, 2, ',', '.') : '—' }}</td><td class="px-5 py-4 text-right text-sm font-bold text-sky-800">{{ number_format((float) $standard->target_value, 2, ',', '.') }}</td><td class="px-5 py-4 text-right text-sm">{{ $standard->maximum_value !== null ? number_format((float) $standard->maximum_value, 2, ',', '.') : '—' }}</td><td class="px-5 py-4 text-xs">{{ $standard->getPeriodStatusLabel() }}</td></tr>@empty<tr><td colspan="7" class="p-14 text-center text-sm">Belum ada standar.</td></tr>@endforelse</tbody></table>
                @elseif ($tab === 'portions')
                    <table class="w-full min-w-[900px] text-left"><thead><tr class="bg-slate-50 text-[10px] font-bold uppercase text-slate-400"><th class="px-5 py-3.5">Bahan / makanan</th><th class="px-5 py-3.5">Komponen</th><th class="px-5 py-3.5">Satuan resep</th><th class="px-5 py-3.5 text-right">Porsi kecil</th><th class="px-5 py-3.5 text-right">SD 1–3</th><th class="px-5 py-3.5 text-right">Porsi besar</th><th class="px-5 py-3.5 text-right">SMP/SMA/Bumil</th><th class="px-5 py-3.5">Sumber</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($portionStandards as $standard)<tr><td class="px-5 py-4"><p class="text-sm font-bold">{{ $standard->ingredient?->name ?? '—' }}</p><p class="text-[10px] text-slate-400">Baris {{ $standard->source_row ?? '—' }}</p></td><td class="px-5 py-4 text-xs">{{ str($standard->component_type)->replace('_',' ')->title() }}</td><td class="px-5 py-4 text-sm">{{ $standard->measurementUnit?->symbol ?? '—' }}</td><td class="px-5 py-4 text-right text-sm font-bold text-sky-800">{{ number_format((float)$standard->small_quantity,2,',','.') }}</td><td class="px-5 py-4 text-right text-sm">{{ number_format((float)$standard->small_quantity,2,',','.') }}</td><td class="px-5 py-4 text-right text-sm font-bold text-indigo-800">{{ number_format((float)$standard->large_quantity,2,',','.') }}</td><td class="px-5 py-4 text-right text-sm">{{ number_format((float)$standard->large_quantity,2,',','.') }}</td><td class="px-5 py-4 text-xs text-slate-500">{{ $standard->source }}</td></tr>@empty<tr><td colspan="8" class="p-14 text-center text-sm">Belum ada standar gramasi bahan. Jalankan seeder referensi MBG.</td></tr>@endforelse</tbody></table>
                @else
                    <div class="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-3">@foreach($measurementUnits as $unitItem)<article class="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div class="flex justify-between"><div><p class="text-sm font-bold">{{ $unitItem->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $unitItem->code }} · {{ $unitItem->unit_type }}</p></div><span class="rounded-lg bg-white px-2 py-1 text-xs font-bold text-sky-800">{{ $unitItem->symbol }}</span></div><p class="mt-4 text-xs text-slate-400">Faktor dasar: {{ $unitItem->to_base_factor }}</p></article>@endforeach</div>
                @endif
            </div>
        </section>
    </div>
</x-v3.shell>
