<x-v3.shell :$unit :$navigation :$roleLabel title="Master & Kebutuhan Non-Pangan" eyebrow="Gudang Non-Pangan">
    <div class="mx-auto max-w-[1400px] space-y-5">
        @if($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif
        <section class="rounded-[28px] bg-[#081d3a] p-6 text-white shadow-xl"><h2 class="text-2xl font-bold">Barang operasional terpisah dari bahan gizi</h2><p class="mt-2 text-sm text-slate-300">Stok tetap dicatat pada engine yang sama. Sistem menampilkan stok tersedia, batas minimum, target, dan saran pengadaan.</p><div class="mt-4 flex gap-2"><a wire:navigate href="{{ route('v3.warehouse.opening-stocks.index', ['gudang'=>'non_food']) }}" class="rounded-xl bg-cyan-300 px-4 py-3 text-xs font-bold text-[#081d3a]">Input Stok Awal</a><a wire:navigate href="{{ route('v3.warehouse.stock.index', ['gudang'=>'non_food']) }}" class="rounded-xl bg-white/10 px-4 py-3 text-xs font-bold">Kartu Stok</a></div></section>

        @if(auth()->user()->is_super_admin || auth()->user()->can('non_food_items.manage'))
        <form wire:submit="save" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">{{ $editingId ? 'Ubah' : 'Tambah' }} barang Non-Pangan</h3><div class="mt-4 grid gap-3 md:grid-cols-4"><label><span class="text-xs font-semibold">Kode *</span><input wire:model="code" class="mt-1 h-10 w-full rounded-xl border-slate-200" placeholder="NP-SARUNG-TANGAN"></label><label><span class="text-xs font-semibold">Nama *</span><input wire:model="name" class="mt-1 h-10 w-full rounded-xl border-slate-200"></label><label><span class="text-xs font-semibold">Kategori *</span><select wire:model="category" class="mt-1 h-10 w-full rounded-xl border-slate-200">@foreach($categories as $category)<option>{{ $category }}</option>@endforeach</select></label><label><span class="text-xs font-semibold">Satuan *</span><select wire:model="measurementUnitId" class="mt-1 h-10 w-full rounded-xl border-slate-200"><option value="">Pilih</option>@foreach($measurementUnits as $unitItem)<option value="{{ $unitItem->id }}">{{ $unitItem->name }} ({{ $unitItem->symbol ?: $unitItem->code }})</option>@endforeach</select></label><label><span class="text-xs font-semibold">Stok minimum</span><input wire:model="minimumStock" type="number" step=".0001" class="mt-1 h-10 w-full rounded-xl border-slate-200"></label><label><span class="text-xs font-semibold">Target stok</span><input wire:model="targetStock" type="number" step=".0001" class="mt-1 h-10 w-full rounded-xl border-slate-200"></label><label><span class="text-xs font-semibold">Lokasi default</span><input wire:model="defaultLocation" class="mt-1 h-10 w-full rounded-xl border-slate-200"></label><div class="flex items-end gap-4 pb-2"><label class="text-xs"><input wire:model="tracksLot" type="checkbox"> Lacak lot</label><label class="text-xs"><input wire:model="tracksExpiry" type="checkbox"> Lacak expired</label></div></div>@if($errors->any())<p class="mt-3 text-xs text-rose-600">{{ $errors->first() }}</p>@endif<div class="mt-4"><button class="rounded-xl bg-sky-600 px-5 py-3 text-xs font-bold text-white">Simpan master</button></div></form>
        @endif

        <form wire:submit="createProcurement" class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h3 class="font-bold text-slate-900">Stok dan kebutuhan Non-Pangan</h3><p class="mt-1 text-xs text-slate-500">Isi jumlah pengadaan hanya untuk barang yang akan diajukan. Nilai awal mengikuti saran sistem.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead><tr class="bg-slate-50 text-xs text-slate-500"><th class="p-4">Barang</th><th class="p-4">Kategori</th><th class="p-4 text-right">Tersedia</th><th class="p-4 text-right">Minimum</th><th class="p-4 text-right">Target</th><th class="p-4">Jumlah diajukan</th><th class="p-4"></th></tr></thead><tbody class="divide-y">@foreach($items as $item)<tr><td class="p-4"><p class="font-bold text-slate-800">{{ $item->name }}</p><p class="text-xs text-slate-400">{{ $item->code }} · {{ $item->measurementUnit?->symbol }}</p></td><td class="p-4 text-sm">{{ $item->category }}</td><td class="p-4 text-right font-bold">{{ number_format($item->availableQuantity(),4,',','.') }}</td><td class="p-4 text-right">{{ number_format((float)$item->minimum_stock,4,',','.') }}</td><td class="p-4 text-right">{{ number_format((float)$item->target_stock,4,',','.') }}</td><td class="p-4"><input wire:model="quantities.{{ $item->id }}" type="number" min="0" step=".0001" class="h-10 w-36 rounded-xl border-slate-200"></td><td class="p-4"><button wire:click="edit({{ $item->id }})" type="button" class="text-xs font-bold text-sky-700">Ubah</button></td></tr>@endforeach</tbody></table></div>@if(auth()->user()->is_super_admin || auth()->user()->can('non_food_procurement.create'))<div class="grid gap-3 border-t p-5 md:grid-cols-[200px_1fr_auto]"><input wire:model="neededDate" type="date" min="{{ today()->toDateString() }}" class="h-11 rounded-xl border-slate-200"><input wire:model="procurementNotes" class="h-11 rounded-xl border-slate-200" placeholder="Catatan/alasan jumlah manual"><button class="rounded-xl bg-emerald-600 px-5 text-xs font-bold text-white">Buat Draft Pengadaan</button></div>@endif @error('quantities')<p class="px-5 pb-4 text-xs text-rose-600">{{ $message }}</p>@enderror</form>
    </div>
</x-v3.shell>
