<x-v3.shell :$unit :$navigation :$roleLabel title="Pengambilan Gudang" eyebrow="Divisi mengambil, Gudang memeriksa">
<div class="mx-auto max-w-[1450px] space-y-5">
 @if(session('v3.status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('v3.status') }}</div>@endif
 <section class="rounded-[28px] bg-[#081d3a] p-6 text-white"><p class="text-xs font-bold uppercase tracking-widest text-cyan-200">Alur sederhana</p><h2 class="mt-2 text-2xl font-bold">Ambil langsung, catat, lalu cek di tempat.</h2><p class="mt-2 text-sm text-slate-300">Stok belum berubah saat divisi mengajukan. Stok lot baru berkurang setelah staf Gudang memverifikasi sebelum bahan meninggalkan area.</p></section>
 <div class="grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]">
  @if($canTake)
  <form wire:submit="submit" class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <h3 class="font-bold text-slate-950">Catat bahan yang diambil</h3>
   <label class="mt-4 block"><span class="text-xs font-semibold">Untuk proses/batch</span><input wire:model="purposeReference" class="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Contoh: Produksi 20 Juli / Menu hari 1">@error('purposeReference')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
   <div class="mt-4 space-y-3">@foreach($rows as $i => $row)<div class="rounded-xl bg-slate-50 p-3" wire:key="row-{{ $i }}"><select wire:model="rows.{{ $i }}.inventory_lot_id" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih lot (FEFO teratas)</option>@foreach($lots as $lot)<option value="{{ $lot->id }}">{{ $lot->ingredient->name }} — {{ $lot->lot_number ?: 'tanpa batch' }} — {{ number_format((float)$lot->balance_quantity_kg,3,',','.') }} kg — exp {{ $lot->expired_date?->format('d-m-Y') ?? '-' }}</option>@endforeach</select><div class="mt-2 flex gap-2"><input wire:model="rows.{{ $i }}.quantity_kg" type="number" step="0.001" min="0.001" class="h-10 flex-1 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Jumlah kg">@if(count($rows)>1)<button type="button" wire:click="removeRow({{ $i }})" class="px-3 text-xs font-bold text-rose-600">Hapus</button>@endif</div></div>@endforeach</div>
   <button type="button" wire:click="addRow" class="mt-3 text-xs font-bold text-sky-700">+ Tambah bahan</button>
   <textarea wire:model="notes" rows="2" class="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Catatan opsional"></textarea>
   <button class="mt-4 h-11 w-full rounded-xl bg-sky-600 text-xs font-bold text-white">Ajukan pengecekan Gudang</button>
  </form>
  @else<div class="h-fit rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Pencatatan pengambilan hanya untuk petugas Persiapan, Pengolahan, dan Pemorsian.</div>@endif
  <section class="space-y-3"><div class="rounded-2xl border border-slate-200 bg-white p-4"><h3 class="font-bold">Antrean dan riwayat</h3>@if($canVerify)<textarea wire:model="decisionNotes" class="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm" rows="2" placeholder="Alasan wajib untuk koreksi/penolakan"></textarea>@endif</div>
  @forelse($records as $record)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $record->withdrawal_number }}</p><p class="text-xs text-slate-500">{{ ucfirst($record->division_code) }} · {{ $record->taker?->name }} · {{ $record->purpose_reference }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{{ str($record->status)->replace('_',' ')->title() }}</span></div><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($record->items as $item)<div class="rounded-xl bg-slate-50 px-3 py-2 text-xs"><b>{{ $item->ingredient_name_snapshot }}</b><br>{{ number_format((float)$item->taken_quantity_kg,3,',','.') }} kg · lot {{ $item->lot_number_snapshot ?: '-' }}</div>@endforeach</div>@if($record->decision_notes)<p class="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{{ $record->decision_notes }}</p>@endif @if($canVerify && $record->status===\App\Models\WarehouseWithdrawal::WAITING)<div class="mt-4 flex flex-wrap justify-end gap-2"><button wire:click="reject({{ $record->id }})" class="rounded-xl px-3 py-2 text-xs font-bold text-rose-600">Tolak</button><button wire:click="revise({{ $record->id }})" class="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">Minta koreksi</button><button wire:click="verify({{ $record->id }})" class="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Verifikasi & kurangi stok</button></div>@endif</article>@empty<div class="rounded-2xl bg-white p-10 text-center text-sm text-slate-500">Belum ada pengambilan.</div>@endforelse {{ $records->links() }}</section>
 </div>
</div>
</x-v3.shell>