<x-v3.shell :$unit :$navigation :$roleLabel :title="$config['label']" eyebrow="Katalog master data">
    <div class="mx-auto max-w-[1500px] space-y-5">
        <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
            <div><a wire:navigate href="{{ route('v3.master-data.index') }}" class="inline-flex items-center gap-2 text-xs font-bold text-sky-700"><x-v3.icon name="arrow-left" class="size-4" /> Pusat master data</a><h2 class="mt-3 text-2xl font-bold tracking-tight text-slate-950">{{ $config['label'] }}</h2><p class="mt-1 text-sm text-slate-500">{{ $config['description'] }}</p></div>
            @if ($canCreate)<button wire:click="create" class="h-11 rounded-xl bg-[#081d3a] px-5 text-xs font-bold text-white">Tambah data</button>@endif
        </div>

        @if ($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror

        <div class="grid gap-5 xl:grid-cols-[430px_minmax(0,1fr)]">
            @if ($canCreate || ($recordId && $canUpdate))
                <form wire:submit="save" class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-24">
                    <div class="flex items-start justify-between gap-3"><div><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">{{ $recordId ? 'Ubah data' : 'Data baru' }}</p><h3 class="mt-1 text-base font-bold text-slate-950">{{ $config['label'] }}</h3></div>@if ($recordId)<button type="button" wire:click="cancel" class="text-xs font-bold text-slate-400">Batal</button>@endif</div>
                    <div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-2">
                        @foreach ($config['fields'] as $name => $field)
                            @if ($field['type'] === 'toggle')
                                <label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-3 py-3 sm:col-span-2"><span class="text-xs font-semibold text-slate-700">{{ $field['label'] }}</span><input wire:model="form.{{ $name }}" type="checkbox" class="size-4 rounded border-slate-300 text-sky-600"></label>
                            @elseif ($field['type'] === 'textarea')
                                <label class="block sm:col-span-2"><span class="mb-1.5 block text-xs font-semibold text-slate-600">{{ $field['label'] }}</span><textarea wire:model="form.{{ $name }}" rows="3" class="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"></textarea>@error("form.$name")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                            @elseif ($field['type'] === 'select')
                                <label class="block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">{{ $field['label'] }}</span><select wire:model="form.{{ $name }}" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih</option>@foreach ($fieldOptions[$name] as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>@error("form.$name")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                            @else
                                <label class="block"><span class="mb-1.5 block text-xs font-semibold text-slate-600">{{ $field['label'] }}</span><input wire:model="form.{{ $name }}" type="{{ $field['type'] }}" @if($field['type'] === 'number') step="any" @endif class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@error("form.$name")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                            @endif
                        @endforeach
                    </div>

                    @if ($config['special'] === 'ingredient')
                        <div class="mt-5 border-t border-slate-100 pt-5"><p class="text-xs font-bold text-slate-800">Foto bahan</p>@if($existingPhotoPath)<img src="{{ Storage::disk('public')->url($existingPhotoPath) }}" alt="Foto bahan" class="mt-3 size-20 rounded-xl object-cover">@endif<input wire:model="ingredientPhoto" type="file" accept="image/jpeg,image/png,image/webp" class="mt-3 block w-full text-xs text-slate-500">@error('ingredientPhoto')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</div>
                        <div class="mt-5 border-t border-slate-100 pt-5"><div class="flex items-center justify-between"><p class="text-xs font-bold text-slate-800">Nilai gizi per 100 gram</p><button type="button" wire:click="addNutrition" class="text-xs font-bold text-sky-700">+ Tambah</button></div><div class="mt-3 space-y-3">@foreach($nutritionRows as $index => $row)<div wire:key="nutrition-{{ $index }}" class="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-100"><div class="grid gap-2 sm:grid-cols-2"><select wire:model="nutritionRows.{{ $index }}.nutrition_component_id" class="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs"><option value="">Komponen</option>@foreach($nutritionComponents as $component)<option value="{{ $component->id }}">{{ $component->name }} ({{ $component->unit }})</option>@endforeach</select><input wire:model="nutritionRows.{{ $index }}.value_per_100g" type="number" min="0" step="any" placeholder="Nilai / 100 g" class="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs"><input wire:model="nutritionRows.{{ $index }}.source" placeholder="Sumber data" class="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs"><div class="flex gap-2"><input wire:model="nutritionRows.{{ $index }}.notes" placeholder="Catatan" class="h-10 min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-2 text-xs"><button type="button" wire:click="removeNutrition({{ $index }})" class="px-2 text-xs font-bold text-rose-600">Hapus</button></div></div></div>@endforeach</div>@error('nutritionRows.*')<span class="mt-2 block text-xs text-rose-600">{{ $message }}</span>@enderror</div>
                        <div class="mt-5 border-t border-slate-100 pt-5"><div class="flex items-center justify-between"><p class="text-xs font-bold text-slate-800">Alergen bahan</p><button type="button" wire:click="addAllergen" class="text-xs font-bold text-sky-700">+ Tambah</button></div><div class="mt-3 space-y-3">@foreach($allergenRows as $index => $row)<div wire:key="allergen-{{ $index }}" class="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-100"><div class="grid gap-2 sm:grid-cols-2"><select wire:model="allergenRows.{{ $index }}.allergen_id" class="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs"><option value="">Pilih alergen</option>@foreach($allergens as $allergen)<option value="{{ $allergen->id }}">{{ $allergen->name }}</option>@endforeach</select><label class="flex h-10 items-center gap-2 text-xs text-slate-600"><input wire:model="allergenRows.{{ $index }}.contamination_risk" type="checkbox" class="size-4 rounded"> Risiko kontaminasi silang</label><input wire:model="allergenRows.{{ $index }}.notes" placeholder="Catatan" class="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs"><button type="button" wire:click="removeAllergen({{ $index }})" class="h-10 text-xs font-bold text-rose-600">Hapus</button></div></div>@endforeach</div></div>
                    @endif

                    @if ($config['special'] === 'cleaning')
                        <div class="mt-5 border-t border-slate-100 pt-5"><div class="flex items-center justify-between"><p class="text-xs font-bold text-slate-800">Checklist standar</p><button type="button" wire:click="addChecklist" class="text-xs font-bold text-sky-700">+ Tambah</button></div><div class="mt-3 space-y-3">@foreach($checklistRows as $index => $row)<div wire:key="check-{{ $index }}" class="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-100"><select wire:model="checklistRows.{{ $index }}.category" class="h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs"><option value="preparation">Persiapan</option><option value="surface">Permukaan</option><option value="floor">Lantai</option><option value="equipment">Peralatan</option><option value="waste">Limbah</option><option value="personal_hygiene">Higiene Personal</option><option value="other">Lainnya</option></select><input wire:model="checklistRows.{{ $index }}.item_name" placeholder="Poin pemeriksaan" class="mt-2 h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs"><div class="mt-2 flex items-center justify-between"><label class="flex items-center gap-2 text-xs text-slate-600"><input wire:model="checklistRows.{{ $index }}.is_mandatory" type="checkbox" class="size-4 rounded"> Wajib</label><button type="button" wire:click="removeChecklist({{ $index }})" class="text-xs font-bold text-rose-600">Hapus</button></div></div>@endforeach</div></div>
                    @endif

                    <button type="submit" class="mt-5 h-11 w-full rounded-xl bg-sky-600 text-xs font-bold text-white" wire:loading.attr="disabled">{{ $recordId ? 'Simpan perubahan' : 'Simpan data' }}</button>
                </form>
            @else
                <section class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-800">Akses baca-saja</p><p class="mt-1 text-xs text-slate-500">Anda tidak memiliki izin mengubah katalog ini.</p></section>
            @endif

            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:p-5"><div class="relative flex-1"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-11 place-items-center text-slate-400"><x-v3.icon name="search" class="size-[18px]" /></span><input wire:model.live.debounce.350ms="search" type="search" placeholder="Cari {{ strtolower($config['label']) }}..." class="h-11 w-full rounded-xl border border-slate-200 bg-slate-50/50 pl-11 pr-4 text-sm"></div>@if(array_key_exists('is_active', $config['fields']))<select wire:model.live="status" class="h-11 min-w-44 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select>@endif</div>
                <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead><tr class="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400">@foreach($config['listFields'] as $field)<th class="px-4 py-3.5">{{ $config['fields'][$field]['label'] }}</th>@endforeach @if($canUpdate || $canDelete)<th class="px-4 py-3.5 text-right">Aksi</th>@endif</tr></thead><tbody class="divide-y divide-slate-100">@forelse($records as $record)<tr class="hover:bg-sky-50/30">@foreach($config['listFields'] as $field)@php($value = $record->{$field})<td class="px-4 py-4 text-sm text-slate-600">@if($config['fields'][$field]['type'] === 'select'){{ $fieldOptions[$field][$value] ?? '—' }}@elseif($config['fields'][$field]['type'] === 'date'){{ $value?->translatedFormat('d M Y') ?? '—' }}@else{{ filled($value) ? $value : '—' }}@endif</td>@endforeach @if($canUpdate || $canDelete)<td class="px-4 py-4 text-right"><div class="inline-flex gap-2">@if($canUpdate)<button wire:click="edit({{ $record->id }})" class="rounded-lg bg-sky-50 px-3 py-2 text-[10px] font-bold text-sky-700 ring-1 ring-sky-100">Ubah</button>@endif @if($canDelete)<button wire:click="delete({{ $record->id }})" wire:confirm="Hapus data ini?" class="rounded-lg bg-rose-50 px-3 py-2 text-[10px] font-bold text-rose-700 ring-1 ring-rose-100">Hapus</button>@endif</div></td>@endif</tr>@empty<tr><td colspan="{{ count($config['listFields']) + (($canUpdate || $canDelete) ? 1 : 0) }}" class="px-5 py-16 text-center"><p class="text-sm font-bold text-slate-700">Belum ada data</p><p class="mt-1 text-xs text-slate-400">Tambahkan data pertama atau ubah kata pencarian.</p></td></tr>@endforelse</tbody></table></div>@if($records->hasPages())<div class="border-t border-slate-100 px-5 py-4">{{ $records->links() }}</div>@endif
            </section>
        </div>
    </div>
</x-v3.shell>
