<x-v3.shell :$unit :$navigation :$roleLabel title="Master Data" eyebrow="Satu sumber data operasional">
    <div class="mx-auto max-w-[1450px] space-y-5">
        <section class="relative overflow-hidden rounded-[28px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-7"><div class="absolute -right-20 -top-24 size-72 rounded-full bg-cyan-300/10"></div><div class="relative"><span class="rounded-full bg-cyan-300/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-cyan-200 ring-1 ring-cyan-300/20">Master data operasional</span><h2 class="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">Kelola seluruh master data SPPG.</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Data organisasi, pengguna, penerima, bahan, supplier, dan referensi operasional dikelola dari satu halaman sesuai hak akses pengguna.</p></div></section>

        <section><div class="mb-3"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Organisasi dan akses</p><h3 class="mt-1 text-lg font-bold text-slate-950">Konfigurasi sistem tunggal</h3></div><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            @if(auth()->user()->is_super_admin || auth()->user()->can('units.view') || auth()->user()->can('settings.manage'))<a wire:navigate href="{{ route('v3.master-data.organization') }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200"><div class="flex items-center justify-between"><span class="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><x-v3.icon name="home" class="size-5" /></span><span class="text-xs font-bold text-sky-700">Buka →</span></div><h4 class="mt-4 font-bold text-slate-900">Profil Organisasi</h4><p class="mt-1 text-xs leading-5 text-slate-500">Identitas, kepala, dan kontak unit sistem.</p></a>@endif
            @if($userCount !== null)<a wire:navigate href="{{ route('v3.master-data.users') }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200"><div class="flex items-center justify-between"><span class="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><x-v3.icon name="users" class="size-5" /></span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{{ $userCount }} akun</span></div><h4 class="mt-4 font-bold text-slate-900">Pengguna & Role</h4><p class="mt-1 text-xs leading-5 text-slate-500">Akun, role utama, dan status akses pengguna.</p></a>@endif
        </div></section>

        <section><div class="mb-3"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-sky-700">Katalog operasional</p><h3 class="mt-1 text-lg font-bold text-slate-950">Master yang digunakan lintas proses</h3></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">@foreach($catalogs as $catalog)<a wire:navigate href="{{ route('v3.master-data.catalog', $catalog['slug']) }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200"><div class="flex items-center justify-between"><span class="grid size-10 place-items-center rounded-xl bg-slate-50 text-slate-600 group-hover:bg-sky-50 group-hover:text-sky-700"><x-v3.icon name="clipboard" class="size-5" /></span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{{ number_format($catalog['count'], 0, ',', '.') }} data</span></div><h4 class="mt-4 font-bold text-slate-900">{{ $catalog['label'] }}</h4><p class="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{{ $catalog['description'] }}</p></a>@endforeach</div></section>
    </div>
</x-v3.shell>
