<x-v3.shell :$unit :$navigation :$roleLabel title="Presensi Relawan" eyebrow="RFID masuk dan pulang">
    <div wire:poll.15s class="mx-auto max-w-[1450px] space-y-5">
        <section class="overflow-hidden rounded-[28px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-8">
            <div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
                <div>
                    <p class="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Presensi RFID</p>
                    <h2 class="mt-2 text-2xl font-bold">Kehadiran relawan SPPG</h2>
                    <p class="mt-2 max-w-2xl text-sm text-slate-300">Jam kerja fleksibel. Tap pertama mencatat masuk, tap berikutnya mencatat pulang, dan masuk kembali dapat dilakukan enam jam setelah pulang.</p>
                </div>
                <div class="grid grid-cols-2 gap-2 sm:grid-cols-4">
                    <div class="rounded-2xl border border-white/10 bg-white/[.07] px-4 py-3"><p class="text-[10px] uppercase text-slate-400">Hadir</p><p class="mt-1 text-xl font-bold">{{ $summary['present'] }}</p></div>
                    <div class="rounded-2xl border border-white/10 bg-white/[.07] px-4 py-3"><p class="text-[10px] uppercase text-slate-400">Bekerja</p><p class="mt-1 text-xl font-bold text-cyan-300">{{ $summary['working'] }}</p></div>
                    <div class="rounded-2xl border border-white/10 bg-white/[.07] px-4 py-3"><p class="text-[10px] uppercase text-slate-400">Selesai</p><p class="mt-1 text-xl font-bold text-emerald-300">{{ $summary['finished'] }}</p></div>
                    <div class="rounded-2xl border border-white/10 bg-white/[.07] px-4 py-3"><p class="text-[10px] uppercase text-slate-400">Lainnya</p><p class="mt-1 text-xl font-bold text-amber-300">{{ $summary['other'] }}</p></div>
                </div>
            </div>
        </section>

        @if($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror

        @if($revealedDeviceKey)
            <section class="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950">
                <p class="font-bold">Salin kredensial perangkat sekarang</p>
                <p class="mt-1 text-xs">Kunci hanya ditampilkan sekali dan tidak dapat dilihat kembali.</p>
                <div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-white p-3"><p class="text-[10px] font-bold uppercase text-amber-700">DEVICE_CODE</p><code class="mt-1 block break-all text-sm">{{ $revealedDeviceCode }}</code></div><div class="rounded-xl bg-white p-3"><p class="text-[10px] font-bold uppercase text-amber-700">DEVICE_KEY</p><code class="mt-1 block break-all text-sm">{{ $revealedDeviceKey }}</code></div></div>
            </section>
        @endif

        <nav class="flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">
            @foreach(['attendance'=>'Kehadiran','correction'=>'Input & koreksi','registration'=>'Daftarkan kartu','devices'=>'Perangkat','taps'=>'Riwayat tap'] as $tab=>$label)
                @if($tab === 'attendance' || ($tab === 'correction' && $canCorrect) || ($tab === 'registration' && $canManage) || ($tab === 'devices' && $canDevices) || $tab === 'taps')
                    <button wire:click="$set('activeTab','{{ $tab }}')" class="h-10 shrink-0 rounded-xl px-4 text-sm font-bold {{ $activeTab === $tab ? 'bg-sky-600 text-white' : 'text-slate-600 hover:bg-slate-50' }}">{{ $label }}</button>
                @endif
            @endforeach
        </nav>

        @if($activeTab === 'attendance')
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <div class="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 md:flex-row md:items-end">
                    <div><h3 class="font-bold text-slate-900">Kehadiran per tanggal masuk</h3><p class="mt-1 text-xs text-slate-500">Sesi yang melewati tengah malam tetap berada pada tanggal masuk.</p></div>
                    <div class="flex flex-col gap-2 sm:flex-row"><input wire:model.live="filterDate" type="date" class="h-10 rounded-xl border border-slate-200 px-3 text-sm"><input wire:model.live.debounce.350ms="search" type="search" class="h-10 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Cari nama atau UID">@if($canExport)<a href="{{ route('v3.attendance.pdf', ['date_from'=>$filterDate,'date_to'=>$filterDate]) }}" target="_blank" class="inline-flex h-10 items-center justify-center rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-700">PDF</a><a href="{{ route('v3.attendance.xlsx', ['date_from'=>$filterDate,'date_to'=>$filterDate]) }}" class="inline-flex h-10 items-center justify-center rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Excel</a>@endif @if($canReset && $sessions->isNotEmpty())<button wire:click="openResetPanel" type="button" class="inline-flex h-10 items-center justify-center rounded-xl bg-rose-50 px-4 text-xs font-bold text-rose-700">Reset tanggal ini</button>@endif</div>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full min-w-[920px] text-left"><thead><tr class="border-b border-slate-100 bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><th class="px-5 py-3">Relawan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Masuk</th><th class="px-5 py-3">Pulang</th><th class="px-5 py-3">Durasi</th><th class="px-5 py-3">Sumber</th><th class="px-5 py-3">Catatan</th>@if($canCorrect)<th class="px-5 py-3 text-right">Aksi</th>@endif</tr></thead>
                        <tbody class="divide-y divide-slate-100">@forelse($sessions as $session)<tr><td class="px-5 py-4"><p class="text-sm font-bold text-slate-800">{{ $session->user->name }}</p><p class="mt-0.5 text-xs text-slate-400">UID {{ $session->user->employee_number ?: 'belum terdaftar' }} · {{ $session->user->divisions->first()?->name ?: \App\Enums\UserRole::labelFor($session->user->roles->first()?->name) }}</p></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{ $session->status === 'present' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ ['present'=>'Hadir','permission'=>'Izin','sick'=>'Sakit','absent'=>'Tidak hadir'][$session->status] ?? $session->status }}</span></td><td class="px-5 py-4 text-sm text-slate-700">{{ $session->check_in_at?->format('H:i') ?: '—' }}</td><td class="px-5 py-4 text-sm text-slate-700">{{ $session->check_out_at?->format('d/m H:i') ?: 'Masih bekerja' }}</td><td class="px-5 py-4 text-sm font-semibold text-slate-700">@if($session->durationMinutes() !== null){{ intdiv($session->durationMinutes(),60) }}j {{ $session->durationMinutes()%60 }}m @else—@endif</td><td class="px-5 py-4 text-xs text-slate-500">{{ $session->source === 'manual' ? 'Manual' : ($session->source === 'rfid_offline' ? 'RFID offline' : 'RFID') }}</td><td class="max-w-[220px] px-5 py-4 text-xs text-slate-500">{{ $session->notes ?: '—' }}</td>@if($canCorrect)<td class="px-5 py-4 text-right"><button wire:click="editSession({{ $session->id }})" class="rounded-lg bg-sky-50 px-3 py-2 text-xs font-bold text-sky-700">Koreksi</button></td>@endif</tr>@empty<tr><td colspan="8" class="p-10 text-center text-sm text-slate-400">Belum ada data presensi pada tanggal ini.</td></tr>@endforelse</tbody>
                    </table>
                </div>
            </section>

            @if($showResetPanel && $canReset)
                <section class="rounded-2xl border border-rose-200 bg-rose-50 p-5 shadow-sm sm:p-6">
                    <div class="flex items-start gap-3">
                        <span class="mt-1 size-2 shrink-0 rounded-full bg-rose-500"></span>
                        <div>
                            <h3 class="font-bold text-rose-950">Reset presensi tanggal {{ \Carbon\Carbon::parse($filterDate)->format('d/m/Y') }}</h3>
                            <p class="mt-1 text-sm text-rose-800">Seluruh data presensi pada tanggal ini akan disembunyikan dari laporan. Riwayat tap RFID tetap disimpan dan data reset tetap dapat diaudit.</p>
                        </div>
                    </div>
                    <div class="mt-5 grid gap-4 sm:grid-cols-2">
                        <label><span class="mb-1 block text-xs font-semibold text-rose-900">Alasan reset *</span><textarea wire:model="resetReason" rows="3" class="w-full rounded-xl border border-rose-200 bg-white px-3 py-2 text-sm" placeholder="Jelaskan alasan data perlu direset"></textarea>@error('resetReason')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                        <label><span class="mb-1 block text-xs font-semibold text-rose-900">Ketik RESET untuk konfirmasi *</span><input wire:model="resetConfirmation" type="text" autocomplete="off" class="h-11 w-full rounded-xl border border-rose-200 bg-white px-3 text-sm" placeholder="RESET">@error('resetConfirmation')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                    </div>
                    <div class="mt-5 flex flex-wrap justify-end gap-2"><button wire:click="$set('showResetPanel', false)" type="button" class="h-11 rounded-xl border border-rose-200 bg-white px-5 text-sm font-bold text-slate-700">Batal</button><button wire:click="resetAttendance" wire:loading.attr="disabled" type="button" class="h-11 rounded-xl bg-rose-600 px-5 text-sm font-bold text-white disabled:opacity-50">Reset data presensi</button></div>
                </section>
            @endif
        @endif

        @if($activeTab === 'correction' && $canCorrect)
            <form wire:submit="saveManual" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
                <div><h3 class="text-lg font-bold text-slate-900">{{ $sessionId ? 'Koreksi presensi' : 'Tambah presensi manual' }}</h3><p class="mt-1 text-sm text-slate-500">Setiap perubahan disimpan dalam riwayat audit dan wajib memiliki alasan.</p></div>
                <div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <label class="md:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Relawan *</span><select wire:model="manualUserId" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih relawan</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} · {{ $user->employee_number ?: 'UID kosong' }}</option>@endforeach</select>@error('manualUserId')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label><span class="mb-1 block text-xs font-semibold text-slate-600">Tanggal kerja *</span><input wire:model="manualWorkDate" type="date" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm">@error('manualWorkDate')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label><span class="mb-1 block text-xs font-semibold text-slate-600">Status *</span><select wire:model.live="manualStatus" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="present">Hadir</option><option value="permission">Izin</option><option value="sick">Sakit</option><option value="absent">Tidak hadir</option></select></label>
                    @if($manualStatus === 'present')<label><span class="mb-1 block text-xs font-semibold text-slate-600">Jam masuk *</span><input wire:model="manualCheckIn" type="time" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm">@error('manualCheckIn')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label><span class="mb-1 block text-xs font-semibold text-slate-600">Jam pulang</span><input wire:model="manualCheckOut" type="time" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><span class="mt-1 block text-[10px] text-slate-400">Jika lebih kecil dari jam masuk, dianggap hari berikutnya.</span></label>@endif
                    <label class="md:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Catatan</span><input wire:model="manualNotes" type="text" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Opsional"></label>
                    <label class="md:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Alasan input/koreksi *</span><textarea wire:model="manualReason" rows="3" class="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" placeholder="Contoh: relawan lupa membawa kartu">@error('manualReason')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</textarea></label>
                </div>
                <div class="mt-5 flex justify-end"><button type="submit" class="h-11 rounded-xl bg-sky-600 px-5 text-sm font-bold text-white">{{ $sessionId ? 'Simpan koreksi' : 'Tambah presensi' }}</button></div>
            </form>
        @endif

        @if($activeTab === 'registration' && $canManage)
            <div class="grid gap-5 lg:grid-cols-2">
                <form wire:submit="startRegistration" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="text-lg font-bold text-slate-900">Daftarkan kartu RFID</h3><p class="mt-1 text-sm text-slate-500">Pilih relawan dan alat, lalu tempelkan kartu dalam dua menit.</p><div class="mt-5 space-y-4"><label class="block"><span class="mb-1 block text-xs font-semibold text-slate-600">Relawan *</span><select wire:model="registrationUserId" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih relawan</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} · {{ $user->employee_number ?: 'belum ada UID' }}</option>@endforeach</select>@error('registrationUserId')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="block"><span class="mb-1 block text-xs font-semibold text-slate-600">Perangkat *</span><select wire:model="registrationDeviceId" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih perangkat</option>@foreach($devices->where('is_active',true) as $device)<option value="{{ $device->id }}">{{ $device->name }} · {{ $device->location ?: $device->code }}</option>@endforeach</select>@error('registrationDeviceId')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label></div><div class="mt-5 flex justify-end"><button class="h-11 rounded-xl bg-sky-600 px-5 text-sm font-bold text-white">Aktifkan pendaftaran</button></div></form>
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="text-lg font-bold text-slate-900">Status pendaftaran</h3>@if($activeRegistration)<div class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p class="text-xs font-bold uppercase text-amber-700">Menunggu kartu ditempel</p><p class="mt-2 text-lg font-bold text-amber-950">{{ $activeRegistration->user->name }}</p><p class="mt-1 text-sm text-amber-800">Perangkat: {{ $activeRegistration->device->name }} · berakhir {{ $activeRegistration->expires_at->format('H:i:s') }}</p><button wire:click="cancelRegistration({{ $activeRegistration->id }})" class="mt-4 text-xs font-bold text-rose-600">Batalkan pendaftaran</button></div>@else<p class="mt-5 rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">Tidak ada pendaftaran kartu yang aktif.</p>@endif</section>
            </div>
        @endif

        @if($activeTab === 'devices' && $canDevices)
            <div class="grid gap-5 xl:grid-cols-[420px_1fr]">
                <form wire:submit="createDevice" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">Tambah perangkat RFID</h3><div class="mt-4 space-y-3"><label class="block"><span class="mb-1 block text-xs font-semibold text-slate-600">Nama perangkat *</span><input wire:model="deviceName" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Contoh: Presensi pintu utama">@error('deviceName')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="block"><span class="mb-1 block text-xs font-semibold text-slate-600">Kode perangkat *</span><input wire:model="deviceCode" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm uppercase" placeholder="RFID-UTAMA">@error('deviceCode')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="block"><span class="mb-1 block text-xs font-semibold text-slate-600">Lokasi</span><input wire:model="deviceLocation" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Pintu masuk"></label></div><button class="mt-5 h-11 w-full rounded-xl bg-sky-600 text-sm font-bold text-white">Buat perangkat</button></form>
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">Daftar perangkat</h3><div class="mt-4 space-y-3">@forelse($devices as $device)<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div class="flex items-center gap-2"><p class="font-bold text-slate-800">{{ $device->name }}</p><span class="rounded-full px-2 py-0.5 text-[10px] font-bold {{ $device->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $device->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $device->code }} · {{ $device->location ?: 'lokasi belum diisi' }}</p><p class="mt-1 text-xs text-slate-400">{{ $device->last_seen_at ? 'Terhubung '.$device->last_seen_at->diffForHumans() : 'Belum pernah terhubung' }}@if($device->firmware_version) · firmware {{ $device->firmware_version }}@endif</p></div><div class="flex gap-2"><button wire:click="rotateDeviceKey({{ $device->id }})" wire:confirm="Ganti kunci? Firmware dengan kunci lama akan langsung ditolak." class="rounded-lg bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">Ganti kunci</button><button wire:click="toggleDevice({{ $device->id }})" class="rounded-lg px-3 py-2 text-xs font-bold {{ $device->is_active ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700' }}">{{ $device->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></div></div></article>@empty<p class="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">Belum ada perangkat presensi.</p>@endforelse</div></section>
            </div>
        @endif

        @if($activeTab === 'taps')
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">20 tap terakhir</h3><div class="mt-4 space-y-2">@forelse($recentTaps as $tap)<article class="flex flex-col justify-between gap-2 rounded-xl border border-slate-200 px-4 py-3 sm:flex-row sm:items-center"><div><p class="text-sm font-bold text-slate-800">{{ $tap->user?->name ?: 'Kartu tidak dikenal' }}</p><p class="mt-0.5 text-xs text-slate-400">{{ $tap->uid_snapshot }} · {{ $tap->device->name }} · {{ $tap->tapped_at->translatedFormat('d M Y H:i:s') }}</p></div><div class="flex items-center gap-2"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{ $tap->result === 'success' ? 'bg-emerald-50 text-emerald-700' : ($tap->result === 'ignored' ? 'bg-slate-100 text-slate-600' : 'bg-amber-50 text-amber-700') }}">{{ ['check_in'=>'Masuk','check_out'=>'Pulang','duplicate_tap'=>'Tap ganda','wait_6_hours'=>'Menunggu 6 jam','uid_not_found'=>'UID tidak dikenal','register_card'=>'Kartu didaftarkan','already_registered'=>'Kartu sudah dipakai'][$tap->action] ?? $tap->action }}</span>@if($tap->is_offline)<span class="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-bold text-violet-700">Sinkron offline</span>@endif</div></article>@empty<p class="p-8 text-center text-sm text-slate-400">Belum ada kartu yang dibaca.</p>@endforelse</div></section>
        @endif
    </div>
</x-v3.shell>
