<x-v3.shell :$unit :$navigation :$roleLabel title="Jam Kerja & Shift" eyebrow="Kepegawaian">
<div class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-bold text-slate-900 dark:text-white">Jam Kerja & Shift</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-300">Atur jadwal per divisi dan pengecualian jadwal pegawai.</p></div><a href="{{ route('v3.attendance.index') }}" wire:navigate class="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800">Kembali ke presensi</a></div>
    @if($actionMessage)<div role="status" class="rounded-xl bg-emerald-50 p-4 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{{ $actionMessage }}</div>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-rose-50 p-4 text-rose-800 dark:bg-rose-950 dark:text-rose-200">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <form wire:submit="saveSchedule" class="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900">
        <h2 class="text-lg font-bold">{{ $scheduleId ? 'Ubah jam kerja' : 'Tambah jam kerja' }}</h2>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <label class="text-sm">Divisi<select wire:model="form.division_id" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"><option value="">Pilih divisi</option>@foreach($divisions as $division)<option value="{{ $division->id }}">{{ $division->name }}</option>@endforeach</select></label>
            <label class="text-sm">Nama shift<input wire:model="form.name" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800" placeholder="Nama jadwal kerja"></label>
            <label class="text-sm">Toleransi terlambat (menit)<input type="number" min="0" max="180" wire:model="form.late_tolerance_minutes" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label>
            <label class="text-sm">Jam masuk<input type="time" wire:model="form.start_time" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label>
            <label class="text-sm">Jam pulang<input type="time" wire:model="form.end_time" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label>
            <label class="text-sm">Berlaku mulai<input type="date" wire:model="form.effective_from" @readonly($scheduleId) min="{{ $scheduleId ? $form['effective_from'] : now()->toDateString() }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label>
            <label class="text-sm">Berlaku sampai (opsional)<input type="date" wire:model="form.effective_until" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label>
        </div>
        <fieldset><legend class="mb-2 text-sm font-semibold">Hari kerja</legend><div class="flex flex-wrap gap-4">@foreach($dayNames as $value => $label)<label class="flex items-center gap-2 text-sm"><input type="checkbox" wire:model="form.work_days" value="{{ $value }}" class="rounded">{{ $label }}</label>@endforeach</div></fieldset>
        <div class="flex flex-wrap gap-5 text-sm"><label class="flex items-center gap-2"><input type="checkbox" wire:model="form.is_default" class="rounded">Jadwal utama divisi</label><label class="flex items-center gap-2"><input type="checkbox" wire:model="form.is_active" class="rounded">Aktif</label></div>
        <p class="text-sm text-slate-500 dark:text-slate-300">Jam pulang yang sama atau lebih awal dari jam masuk dihitung pada hari berikutnya. Jadwal baru tidak membuat ketidakhadiran sebelum tanggal mulai berlaku. Perubahan jadwal yang sudah berjalan berlaku mulai hari ini; catatan sebelumnya tetap disimpan.</p>
        <div class="flex gap-3"><button type="submit" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-sky-600 px-4 py-2 text-sm font-bold text-white hover:bg-sky-700 disabled:opacity-50" wire:loading.attr="disabled">Simpan jam kerja</button>@if($scheduleId)<button type="button" wire:click="resetForms" class="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800">Batal</button>@endif</div>
    </form>
    <section class="space-y-4"><div class="flex flex-wrap items-center gap-3"><h2 class="mr-auto text-lg font-bold">Daftar jam kerja</h2><select aria-label="Filter divisi" wire:model.live="filterDivisionId" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"><option value="">Semua divisi</option>@foreach($divisions as $division)<option value="{{ $division->id }}">{{ $division->name }}</option>@endforeach</select><select aria-label="Filter status" wire:model.live="filterStatus" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"><option value="active">Aktif</option><option value="inactive">Nonaktif</option><option value="all">Semua status</option></select></div>
        <div class="grid gap-4 lg:grid-cols-2">@forelse($schedules as $schedule)<article wire:key="schedule-{{ $schedule->id }}" class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div class="flex items-start justify-between gap-3"><div><p class="text-sm text-slate-500 dark:text-slate-300">{{ $schedule->division?->name }}</p><h3 class="mt-1 font-bold">{{ $schedule->name }}</h3></div><button wire:click="editSchedule({{ $schedule->id }})" class="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800">Ubah</button></div><p class="mt-3 text-xl font-bold">{{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }}{{ $schedule->spansMidnight() ? ' (+1 hari)' : '' }}</p><p class="mt-2 text-sm">{{ collect($schedule->work_days)->map(fn($day) => $dayNames[$day] ?? '')->join(', ') }}</p><p class="mt-2 text-sm text-slate-500 dark:text-slate-300">Toleransi {{ $schedule->late_tolerance_minutes }} menit · {{ $schedule->is_default ? 'Utama divisi' : 'Shift khusus' }} · {{ $schedule->effective_until && $schedule->effective_until->lt(today()) ? 'Berakhir' : ($schedule->is_active ? 'Aktif' : 'Nonaktif') }}</p><p class="mt-1 text-sm">{{ $schedule->effective_from?->format('d-m-Y') }} — {{ $schedule->effective_until?->format('d-m-Y') ?? 'seterusnya' }}</p></article>@empty<p class="p-5 text-slate-500 dark:text-slate-300">Belum ada jadwal. Pegawai tetap dapat melakukan presensi tanpa perhitungan keterlambatan.</p>@endforelse</div>
    </section>
    <form wire:submit="saveAssignment" class="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h2 class="text-lg font-bold">{{ $assignmentId ? 'Ubah shift khusus pegawai' : 'Shift khusus pegawai' }}</h2><p class="text-sm text-slate-500 dark:text-slate-300">Menggantikan jadwal utama selama periode penugasan. Hari di luar jadwal khusus dianggap tidak terjadwal.</p><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm">Pegawai<select wire:model="assignment.user_id" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"><option value="">Pilih pegawai</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label><label class="text-sm">Shift<select wire:model="assignment.attendance_work_schedule_id" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"><option value="">Pilih shift</option>@foreach($availableSchedules as $schedule)<option value="{{ $schedule->id }}">{{ $schedule->division?->name }} — {{ $schedule->name }}</option>@endforeach</select></label><label class="text-sm">Mulai<input type="date" wire:model="assignment.effective_from" @readonly($assignmentId) class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label><label class="text-sm">Sampai (opsional)<input type="date" wire:model="assignment.effective_until" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></label></div><label class="block text-sm">Catatan<textarea wire:model="assignment.notes" rows="2" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800"></textarea></label><label class="flex items-center gap-2 text-sm"><input type="checkbox" wire:model="assignment.is_active" class="rounded">Penugasan aktif</label><div class="flex gap-3"><button class="inline-flex min-h-11 items-center justify-center rounded-xl bg-sky-600 px-4 py-2 text-sm font-bold text-white hover:bg-sky-700 disabled:opacity-50" wire:loading.attr="disabled">Simpan shift pegawai</button>@if($assignmentId)<button type="button" wire:click="resetForms" class="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800">Batal</button>@endif</div></form>
    <section class="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><table class="w-full text-left text-sm"><thead><tr class="border-b border-slate-200 dark:border-slate-700"><th class="p-4">Pegawai</th><th class="p-4">Divisi / shift</th><th class="p-4">Periode</th><th class="p-4">Status</th><th class="p-4">Aksi</th></tr></thead><tbody>@forelse($assignments as $row)<tr wire:key="assignment-{{ $row->id }}" class="border-b border-slate-100 dark:border-slate-800"><td class="p-4">{{ $row->user?->name }}</td><td class="p-4">{{ $row->workSchedule?->division?->name }} / {{ $row->workSchedule?->name }}</td><td class="p-4">{{ $row->effective_from->format('d-m-Y') }} — {{ $row->effective_until?->format('d-m-Y') ?? 'seterusnya' }}</td><td class="p-4">{{ $row->effective_until && $row->effective_until->lt(today()) ? 'Berakhir' : ($row->is_active ? 'Aktif' : 'Nonaktif') }}</td><td class="p-4"><button wire:click="editAssignment({{ $row->id }})" class="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-200 dark:hover:bg-slate-800">Ubah</button></td></tr>@empty<tr><td colspan="5" class="p-5 text-center text-slate-500">Belum ada shift khusus pegawai.</td></tr>@endforelse</tbody></table></section>
</div>
</x-v3.shell>
