<x-v3.shell :$unit :$navigation :$roleLabel :title="$incident ? 'Rincian Insiden Keamanan' : 'Laporkan Insiden'" eyebrow="Kejadian keamanan terpisah">
    <div class="mx-auto max-w-[1000px] space-y-5">
        <div><a wire:navigate href="{{ route('v3.security.index') }}" class="text-xs font-bold text-sky-700">← Kembali ke Keamanan</a><h2 class="mt-3 text-2xl font-bold text-slate-950">{{ $incident?->title ?: 'Insiden keamanan baru' }}</h2><p class="mt-1 text-sm text-slate-500">Gunakan laporan ini untuk kejadian yang memerlukan perhatian atau tindakan segera.</p></div>
        @if($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif
        @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror
        @if($incident)<section class="rounded-2xl bg-[#081d3a] p-5 text-white"><p class="text-xs text-cyan-300">Status insiden</p><p class="mt-1 text-xl font-bold">{{ $incident->status->label() }}</p></section>@endif
        <form wire:submit="save" class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1 block text-xs font-semibold text-slate-600">Waktu kejadian *</span><input wire:model="occurredAt" type="datetime-local" @disabled(!$editable) class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label><label><span class="mb-1 block text-xs font-semibold text-slate-600">Jenis kejadian *</span><select wire:model="category" @disabled(!$editable) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@foreach($categoryOptions as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label><span class="mb-1 block text-xs font-semibold text-slate-600">Tingkat *</span><select wire:model="severity" @disabled(!$editable) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@foreach($severityOptions as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label><span class="mb-1 block text-xs font-semibold text-slate-600">Foto bukti *</span><input wire:model="photo" type="file" accept="image/*" capture="environment" @disabled(!$editable) class="block w-full text-xs">@if($existingPhoto)<x-v3.documentation-button :url="\Illuminate\Support\Facades\Storage::disk('public')->url($existingPhoto)" :title="'Bukti insiden keamanan · '.($incident?->incident_number ?? 'Insiden')" label="Lihat foto saat ini" class="mt-2" />@endif @error('photo')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="sm:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Judul kejadian *</span><input wire:model="title" type="text" @disabled(!$editable) class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label><label class="sm:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Keterangan *</span><textarea wire:model="description" rows="4" @disabled(!$editable) class="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"></textarea></label><label class="sm:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Tindakan langsung</span><textarea wire:model="immediateAction" rows="3" @disabled(!$editable) class="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"></textarea></label>@if($incident)<label class="sm:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Penyelesaian</span><textarea wire:model="resolution" rows="3" @disabled(!$canResolve) class="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"></textarea></label>@endif</div></section>
            @if($editable || $canResolve)<div class="flex flex-wrap justify-end gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">@if($editable)<button type="submit" class="h-10 rounded-xl bg-sky-600 px-5 text-xs font-bold text-white">Simpan Insiden</button>@endif @if($canResolve && $incident?->status !== App\Enums\FieldIncidentStatus::Resolved)<button type="button" wire:click="resolve" wire:confirm="Tandai insiden ini selesai?" class="h-10 rounded-xl bg-emerald-600 px-5 text-xs font-bold text-white">Selesaikan Insiden</button>@endif</div>@endif
        </form>
    </div>
</x-v3.shell>
