<x-v3.shell :$unit :$navigation :$roleLabel title="Penerimaan Manual" eyebrow="Penerimaan supplier tanpa dokumen pengadaan">
    <div class="mx-auto max-w-[1250px] space-y-5">
        <x-v3.flash-alert />
        <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
            <div><p class="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Gudang</p><h2 class="mt-2 text-2xl font-bold text-slate-950">Catat kiriman di luar pengadaan</h2><p class="mt-1 max-w-3xl text-sm text-slate-500">Setiap barang tetap melalui pemeriksaan jumlah, QC, dan dokumentasi. Hanya jumlah baik yang nantinya masuk kartu stok.</p></div>
            <a wire:navigate href="{{ route('v3.warehouse.receipts.index', ['gudang' => $warehouseType]) }}" class="inline-flex h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700">Kembali ke penerimaan</a>
        </div>

        <form wire:submit="save" class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div class="mb-5 inline-flex rounded-xl bg-slate-100 p-1"><button wire:click="$set('warehouseType','food')" type="button" class="rounded-lg px-4 py-2 text-xs font-bold {{ $warehouseType === 'food' ? 'bg-[#081d3a] text-white' : 'text-slate-600' }}">Pangan</button><button wire:click="$set('warehouseType','non_food')" type="button" class="rounded-lg px-4 py-2 text-xs font-bold {{ $warehouseType === 'non_food' ? 'bg-[#081d3a] text-white' : 'text-slate-600' }}">Non-Pangan</button></div>
                <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <label><span class="mb-1 block text-xs font-semibold text-slate-600">Tanggal penerimaan *</span><input wire:model="receiptDate" type="date" max="{{ today()->toDateString() }}" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm">@error('receiptDate')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="xl:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Supplier *</span><select wire:model="supplierId" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}{{ $supplier->code ? ' · '.$supplier->code : '' }}</option>@endforeach</select>@error('supplierId')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label><span class="mb-1 block text-xs font-semibold text-slate-600">Catatan umum</span><input wire:model="notes" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Alasan penerimaan manual"></label>
                </div>
            </section>

            <section x-data="{ itemOptions: @js($itemSearchOptions) }" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div class="flex items-center justify-between gap-3"><div><h3 class="font-bold text-slate-900">Barang yang diterima</h3><p class="mt-1 text-xs text-slate-500">Jumlah baik dan ditolak wajib sama dengan jumlah kiriman supplier.</p></div><button wire:click="addRow" type="button" class="h-10 shrink-0 rounded-xl bg-sky-50 px-4 text-xs font-bold text-sky-700">+ Tambah barang</button></div>
                <div class="mt-5 space-y-4">
                    @foreach($rows as $index => $row)
                        @php($itemField = $warehouseType === 'non_food' ? 'non_food_item_id' : 'ingredient_id')
                        <article wire:key="manual-receipt-row-{{ $index }}" class="rounded-2xl border border-slate-200 bg-slate-50/70 p-4">
                            <div class="flex items-center justify-between"><div class="flex items-center gap-2"><span class="grid size-7 place-items-center rounded-lg bg-[#081d3a] text-xs font-bold text-white">{{ $index + 1 }}</span><strong class="text-sm text-slate-800">Pemeriksaan barang</strong></div>@if(count($rows)>1)<button wire:click="removeRow({{ $index }})" type="button" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600">Hapus</button>@endif</div>
                            <div class="mt-4 grid gap-3 md:grid-cols-12">
                                <div x-data="{ open:false, search:@js(collect($itemSearchOptions)->firstWhere('id', (string) ($row[$itemField] ?? ''))['label'] ?? '') }" x-on:click.outside="open=false" class="relative md:col-span-8"><label><span class="mb-1 block text-xs font-semibold text-slate-600">Cari barang *</span><input x-model="search" x-on:focus="open=true" x-on:input="open=true; $wire.set('rows.{{ $index }}.{{ $itemField }}','')" type="search" autocomplete="off" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" placeholder="Ketik nama atau kode barang"></label><div x-show="open" x-transition class="absolute z-30 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl"><template x-for="option in itemOptions.filter(item => item.label.toLowerCase().includes(search.toLowerCase().trim())).slice(0,50)" :key="option.id"><button type="button" x-on:click="search=option.label; open=false; $wire.set('rows.{{ $index }}.{{ $itemField }}',option.id)" class="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-sky-50" x-text="option.label"></button></template><p x-show="itemOptions.filter(item => item.label.toLowerCase().includes(search.toLowerCase().trim())).length===0" class="px-3 py-4 text-center text-xs text-slate-400">Barang tidak ditemukan</p></div>@error("rows.$index.$itemField")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</div>
                                <label class="md:col-span-4"><span class="mb-1 block text-xs font-semibold text-slate-600">Satuan</span><input value="{{ $itemUnits[$row[$itemField] ?? ''] ?? '—' }}" disabled class="h-10 w-full rounded-xl border border-slate-200 bg-slate-100 px-3 text-sm font-semibold text-slate-500"></label>
                                <label class="md:col-span-4"><span class="mb-1 block text-xs font-semibold text-slate-600">Jumlah diterima *</span><input wire:model="rows.{{ $index }}.received_quantity" type="number" min="0" step="0.0001" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@error("rows.$index.received_quantity")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                                <label class="md:col-span-4"><span class="mb-1 block text-xs font-semibold text-slate-600">Jumlah baik *</span><input wire:model="rows.{{ $index }}.accepted_quantity" type="number" min="0" step="0.0001" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@error("rows.$index.accepted_quantity")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                                <label class="md:col-span-4"><span class="mb-1 block text-xs font-semibold text-slate-600">Jumlah ditolak *</span><input wire:model="rows.{{ $index }}.rejected_quantity" type="number" min="0" step="0.0001" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@error("rows.$index.rejected_quantity")<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                                <label class="md:col-span-3"><span class="mb-1 block text-xs font-semibold text-slate-600">Batch supplier</span><input wire:model="rows.{{ $index }}.supplier_batch_number" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>
                                <label class="md:col-span-3"><span class="mb-1 block text-xs font-semibold text-slate-600">Kedaluwarsa</span><input wire:model="rows.{{ $index }}.expired_date" type="date" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>
                                <label class="md:col-span-3"><span class="mb-1 block text-xs font-semibold text-slate-600">Suhu diterima °C</span><input wire:model="rows.{{ $index }}.received_temperature_celsius" type="number" step="0.01" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>
                                <label class="md:col-span-3"><span class="mb-1 block text-xs font-semibold text-slate-600">Catatan mutu</span><input wire:model="rows.{{ $index }}.quality_notes" class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label>
                                <div x-data class="md:col-span-12 rounded-xl border border-slate-200 bg-white p-3"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p class="text-xs font-bold text-slate-700">Dokumentasi barang *</p><p class="mt-1 text-[11px] text-slate-500">Pilih 1–10 foto, maksimal 5 MB per foto.</p></div><input x-ref="photos" wire:model="rows.{{ $index }}.photos" type="file" multiple accept="image/*" capture="environment" class="hidden"><button x-on:click="$refs.photos.click()" type="button" class="h-9 rounded-xl bg-sky-600 px-4 text-xs font-bold text-white">Pilih foto</button></div>@if(!empty($row['photos']))<div class="mt-3 flex flex-wrap gap-2">@foreach($row['photos'] as $photo)<span class="max-w-full truncate rounded-lg bg-sky-50 px-3 py-2 text-[11px] font-semibold text-sky-700">{{ $photo->getClientOriginalName() }}</span>@endforeach</div>@endif @error("rows.$index.photos")<span class="mt-2 block text-xs text-rose-600">{{ $message }}</span>@enderror @error("rows.$index.photos.*")<span class="mt-2 block text-xs text-rose-600">{{ $message }}</span>@enderror</div>
                            </div>
                        </article>
                    @endforeach
                </div>
                <div class="mt-5 flex flex-col justify-between gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center"><p class="text-xs text-slate-500">Dokumen disimpan sebagai <strong>Draft Penerimaan Manual</strong> sebelum stok dikunci.</p><button type="submit" wire:loading.attr="disabled" class="h-11 rounded-xl bg-emerald-600 px-6 text-sm font-bold text-white disabled:opacity-50"><span wire:loading.remove wire:target="save">Simpan dan periksa draft</span><span wire:loading wire:target="save">Menyimpan...</span></button></div>
            </section>
        </form>
    </div>
</x-v3.shell>
