<x-v3.shell :$unit :$navigation :$roleLabel title="Rincian Penerimaan" eyebrow="Kuantitas, batch, dan QC">
    <div class="mx-auto max-w-[1450px] space-y-5">
        <div class="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div><a wire:navigate href="{{ route('v3.warehouse.receipts.index') }}" class="inline-flex items-center gap-2 text-xs font-bold text-sky-700"><x-v3.icon name="arrow-left" class="size-4" /> Kembali ke penerimaan</a><h2 class="mt-3 text-2xl font-bold tracking-tight text-slate-950">{{ $receipt->receipt_number }}</h2><p class="mt-1 text-sm text-slate-500">{{ $receipt->procurementRequest?->request_number ?? 'Penerimaan manual' }} · {{ $receipt->receipt_date?->translatedFormat('d M Y') }}</p></div><div class="flex flex-wrap gap-2">@if ($receipt->procurementRequest)<a wire:navigate href="{{ route('v3.procurement.show', $receipt->procurementRequest) }}" class="inline-flex h-10 items-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600">Buka permintaan</a>@endif @if ($receipt->status === \App\Models\StockReceipt::STATUS_RECEIVED && (auth()->user()->is_super_admin || auth()->user()->can('stock.create')))<button wire:click="createHandover" wire:confirm="Buat atau buka dokumen serah bahan?" class="h-10 rounded-xl bg-amber-500 px-4 text-xs font-bold text-white">Serahkan ke Persiapan</button>@endif</div></div>
        @if ($actionMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ $actionMessage }}</div>@endif @error('action')<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $message }}</div>@enderror

        <section class="rounded-[26px] bg-[#081d3a] p-6 text-white shadow-xl sm:p-7"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span class="rounded-full bg-emerald-300/10 px-3 py-1 text-[10px] font-bold text-emerald-200 ring-1 ring-emerald-300/20">{{ $statuses[$receipt->status] ?? '-' }}</span><h3 class="mt-4 text-2xl font-bold">{{ $receipt->items->count() }} item diperiksa</h3><p class="mt-2 text-sm text-slate-300">{{ $receipt->notes ?: 'Lengkapi hasil fisik dan QC sebelum memasukkan stok.' }}</p></div><div class="grid grid-cols-3 gap-3"><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Dipesan</p><p class="mt-1 text-lg font-bold">{{ number_format((float) $receipt->items->sum('ordered_quantity_kg'), 2, ',', '.') }} kg</p></div><div class="rounded-xl border border-white/10 bg-white/[.07] p-3"><p class="text-[10px] text-slate-400">Diterima baik</p><p class="mt-1 text-lg font-bold">{{ number_format((float) $receipt->items->sum('accepted_quantity_kg'), 2, ',', '.') }} kg</p></div><div class="rounded-xl border border-rose-300/20 bg-rose-300/10 p-3"><p class="text-[10px] text-rose-200/70">Ditolak</p><p class="mt-1 text-lg font-bold text-rose-100">{{ number_format((float) $receipt->items->sum('rejected_quantity_kg'), 2, ',', '.') }} kg</p></div></div></div></section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 md:grid-cols-3"><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Tanggal terima</span><input wire:model="receiptDate" type="date" @disabled(! $canEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Petugas penerima</span><input wire:model="receivedByName" type="text" @disabled(! $canEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Catatan dokumen</span><input wire:model="notes" type="text" @disabled(! $canEdit) class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm disabled:opacity-60"></label></div></section>

        <section class="space-y-4">
            @foreach ($receipt->items as $item)
                <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col justify-between gap-2 border-b border-slate-100 pb-4 sm:flex-row sm:items-center"><div><h3 class="text-base font-bold text-slate-950">{{ $item->ingredient_name_snapshot }}</h3><p class="mt-1 text-xs text-slate-400">Dipesan {{ number_format((float) $item->ordered_quantity, 4, ',', '.') }} {{ $item->unit_snapshot }} / {{ number_format((float) $item->ordered_quantity_kg, 3, ',', '.') }} kg · {{ $item->supplier?->name ?? 'Supplier tidak tersedia' }}</p></div><span class="w-fit rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 ring-1 ring-slate-200">{{ ['pending' => 'Belum dicek', 'accepted' => 'Layak', 'partial' => 'Sebagian ditolak', 'rejected' => 'Ditolak'][$item->quality_status] ?? '-' }}</span></div>
                    <div class="mt-4 grid gap-4 sm:grid-cols-3 xl:grid-cols-6"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Diterima ({{ $item->unit_snapshot }})</span><input wire:model="rows.{{ $item->id }}.received_quantity" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Baik</span><input wire:model="rows.{{ $item->id }}.accepted_quantity" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Ditolak</span><input wire:model="rows.{{ $item->id }}.rejected_quantity" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Diterima (kg)</span><input wire:model="rows.{{ $item->id }}.received_quantity_kg" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Baik (kg)</span><input wire:model="rows.{{ $item->id }}.accepted_quantity_kg" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Ditolak (kg)</span><input wire:model="rows.{{ $item->id }}.rejected_quantity_kg" type="number" min="0" step="0.0001" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div>
                    <div class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Batch supplier</span><input wire:model="rows.{{ $item->id }}.supplier_batch_number" type="text" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Kedaluwarsa</span><input wire:model="rows.{{ $item->id }}.expired_date" type="date" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Suhu terima (°C)</span><input wire:model="rows.{{ $item->id }}.received_temperature_celsius" type="number" step="0.01" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Status QC</span><select wire:model="rows.{{ $item->id }}.quality_status" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="pending">Belum dicek</option><option value="accepted">Layak</option><option value="partial">Sebagian ditolak</option><option value="rejected">Ditolak</option></select></label><label><span class="mb-1 block text-[11px] font-semibold text-slate-500">Catatan QC</span><input wire:model="rows.{{ $item->id }}.quality_notes" type="text" @disabled(! $canEdit) class="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"></label></div>
                </article>
            @endforeach
        </section>

        @if ($canEdit)<div class="sticky bottom-4 z-10 flex flex-wrap justify-end gap-2 rounded-2xl border border-slate-200 bg-white/90 p-3 shadow-xl backdrop-blur"><button wire:click="delete" wire:confirm="Hapus draft penerimaan ini?" class="h-10 rounded-xl px-4 text-xs font-bold text-rose-700 hover:bg-rose-50">Hapus draft</button><button wire:click="save" class="h-10 rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-700">Simpan QC</button>@if (auth()->user()->is_super_admin || auth()->user()->can('stock.create'))<button wire:click="receive" wire:confirm="Kunci dokumen dan masukkan kuantitas baik ke stok?" class="h-10 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white">Terima & masukkan stok</button>@endif</div>@endif
    </div>
</x-v3.shell>
